from .generate_methods_for_privateuse1_backend import TorchUtilsGeneratemethodsforprivateuse1backendTestCase
from .set_module import TorchUtilsSetmoduleTestCase
from .swap_tensors import TorchUtilsSwaptensorsTestCase
from .rename_privateuse1_backend import TorchUtilsRenameprivateuse1backendTestCase
from .get_cpp_backtrace import TorchUtilsGetcppbacktraceTestCase
