from .lt import TorchTensorLtTestCase
from .matrix_exp import TorchTensorMatrixexpTestCase
from .arccosh import TorchTensorArccoshTestCase
from .index_reduce import TorchTensorIndexreduceTestCase
from .fmod_ import TorchTensorFmodTestCase
from .softmax import TorchTensorSoftmaxTestCase
from .tril import TorchTensorTrilTestCase
from .lgamma_ import TorchTensorLgammaTestCase
from .cumprod import TorchTensorCumprodTestCase
from .expand import TorchTensorExpandTestCase
from .ldexp import TorchTensorLdexpTestCase
from .fill_ import TorchTensorFillTestCase
from .sparse_mask import TorchTensorSparsemaskTestCase
from .bitwise_and import TorchTensorBitwiseandTestCase
from .copysign_ import TorchTensorCopysignTestCase
from .mul_ import TorchTensorMulTestCase
from .expm1_ import TorchTensorExpm1TestCase
from .absolute import TorchTensorAbsoluteTestCase
from .scatter_reduce import TorchTensorScatterreduceTestCase
from .lerp_ import TorchTensorLerpTestCase
from .erfc_ import TorchTensorErfcTestCase
from .bool import TorchTensorBoolTestCase
from .asinh_ import TorchTensorAsinhTestCase
from .igammac_ import TorchTensorIgammacTestCase
from .storage_offset import TorchTensorStorageoffsetTestCase
from .to import TorchTensorToTestCase
from .atanh_ import TorchTensorAtanhTestCase
from .asin import TorchTensorAsinTestCase
from .deg2rad import TorchTensorDeg2radTestCase
from .arcsinh import TorchTensorArcsinhTestCase
from .numpy import TorchTensorNumpyTestCase
from .floor import TorchTensorFloorTestCase
from .fmin import TorchTensorFminTestCase
from .sort import TorchTensorSortTestCase
from .reshape_as import TorchTensorReshapeasTestCase
from .index_put import TorchTensorIndexputTestCase
from .unsqueeze_ import TorchTensorUnsqueezeTestCase
from .cpu import TorchTensorCpuTestCase
from .bitwise_not_ import TorchTensorBitwisenotTestCase
from .untyped_storage import TorchTensorUntypedstorageTestCase
from .qr import TorchTensorQrTestCase
from .baddbmm_ import TorchTensorBaddbmmTestCase
from .arctan2_ import TorchTensorArctan2TestCase
from .char import TorchTensorCharTestCase
from .index_add_ import TorchTensorIndexaddTestCase
from .scatter_add_ import TorchTensorScatteraddTestCase
from .multiply import TorchTensorMultiplyTestCase
from .argmin import TorchTensorArgminTestCase
from .take_along_dim import TorchTensorTakealongdimTestCase
from .norm import TorchTensorNormTestCase
from .greater_equal import TorchTensorGreaterequalTestCase
from .bernoulli import TorchTensorBernoulliTestCase
from .is_leaf import TorchTensorIsleafTestCase
from .to_sparse import TorchTensorTosparseTestCase
from .triu_ import TorchTensorTriuTestCase
from .q_scale import TorchTensorQscaleTestCase
from .gcd import TorchTensorGcdTestCase
from .sgn_ import TorchTensorSgnTestCase
from .cdouble import TorchTensorCdoubleTestCase
from .tan import TorchTensorTanTestCase
from .chunk import TorchTensorChunkTestCase
from .sum_to_size import TorchTensorSumtosizeTestCase
from .diagonal_scatter import TorchTensorDiagonalscatterTestCase
from .greater_equal_ import TorchTensorGreaterequalTestCase
from .hardshrink import TorchTensorHardshrinkTestCase
from .negative import TorchTensorNegativeTestCase
from .cos import TorchTensorCosTestCase
from .q_per_channel_axis import TorchTensorQperchannelaxisTestCase
from .acos_ import TorchTensorAcosTestCase
from .bitwise_left_shift import TorchTensorBitwiseleftshiftTestCase
from .addr_ import TorchTensorAddrTestCase
from .requires_grad_ import TorchTensorRequiresgradTestCase
from .double import TorchTensorDoubleTestCase
from .stride import TorchTensorStrideTestCase
from .float import TorchTensorFloatTestCase
from .share_memory_ import TorchTensorSharememoryTestCase
from .erf import TorchTensorErfTestCase
from .greater import TorchTensorGreaterTestCase
from .square import TorchTensorSquareTestCase
from .flipud import TorchTensorFlipudTestCase
from .log10_ import TorchTensorLog10TestCase
from .cumsum import TorchTensorCumsumTestCase
from .logaddexp2 import TorchTensorLogaddexp2TestCase
from .select import TorchTensorSelectTestCase
from .arccosh_ import TorchTensorArccoshTestCase
from .less_ import TorchTensorLessTestCase
from .lgamma import TorchTensorLgammaTestCase
from .angle import TorchTensorAngleTestCase
from .i0_ import TorchTensorI0TestCase
from .true_divide_ import TorchTensorTruedivideTestCase
from .std import TorchTensorStdTestCase
from .diagonal import TorchTensorDiagonalTestCase
from .fix_ import TorchTensorFixTestCase
from .not_equal import TorchTensorNotequalTestCase
from .cfloat import TorchTensorCfloatTestCase
from .index_fill_ import TorchTensorIndexfillTestCase
from .log1p_ import TorchTensorLog1pTestCase
from .type_as import TorchTensorTypeasTestCase
from .set_ import TorchTensorSetTestCase
from .mvlgamma import TorchTensorMvlgammaTestCase
from .real import TorchTensorRealTestCase
from .remainder_ import TorchTensorRemainderTestCase
from .new_tensor import TorchTensorNewtensorTestCase
from .masked_scatter import TorchTensorMaskedscatterTestCase
from .geqrf import TorchTensorGeqrfTestCase
from .abs import TorchTensorAbsTestCase
from .rot90 import TorchTensorRot90TestCase
from .asin_ import TorchTensorAsinTestCase
from .addr import TorchTensorAddrTestCase
from .lu import TorchTensorLuTestCase
from .get_device import TorchTensorGetdeviceTestCase
from .pow_ import TorchTensorPowTestCase
from .neg_ import TorchTensorNegTestCase
from .where import TorchTensorWhereTestCase
from .triangular_solve import TorchTensorTriangularsolveTestCase
from .mm import TorchTensorMmTestCase
from .type import TorchTensorTypeTestCase
from .sigmoid import TorchTensorSigmoidTestCase
from .atan2 import TorchTensorAtan2TestCase
from .inverse import TorchTensorInverseTestCase
from .addmv_ import TorchTensorAddmvTestCase
from .svd import TorchTensorSvdTestCase
from .squeeze import TorchTensorSqueezeTestCase
from .erfinv import TorchTensorErfinvTestCase
from .size import TorchTensorSizeTestCase
from .trunc_ import TorchTensorTruncTestCase
from .eq_ import TorchTensorEqTestCase
from .index_add import TorchTensorIndexaddTestCase
from .resolve_neg import TorchTensorResolvenegTestCase
from .tan_ import TorchTensorTanTestCase
from .dequantize import TorchTensorDequantizeTestCase
from .frac import TorchTensorFracTestCase
from .cholesky import TorchTensorCholeskyTestCase
from .cov import TorchTensorCovTestCase
from .ceil import TorchTensorCeilTestCase
from .triu import TorchTensorTriuTestCase
from .exp_ import TorchTensorExpTestCase
from .all import TorchTensorAllTestCase
from .to_mkldnn import TorchTensorTomkldnnTestCase
from .divide_ import TorchTensorDivideTestCase
from .i0 import TorchTensorI0TestCase
from .is_sparse import TorchTensorIssparseTestCase
from .round_ import TorchTensorRoundTestCase
from .transpose import TorchTensorTransposeTestCase
from .movedim import TorchTensorMovedimTestCase
from .bernoulli_ import TorchTensorBernoulliTestCase
from .nelement import TorchTensorNelementTestCase
from .storage import TorchTensorStorageTestCase
from .dim_order import TorchTensorDimorderTestCase
from .median import TorchTensorMedianTestCase
from .tile import TorchTensorTileTestCase
from .expand_as import TorchTensorExpandasTestCase
from .isinf import TorchTensorIsinfTestCase
from .scatter_reduce_ import TorchTensorScatterreduceTestCase
from .kthvalue import TorchTensorKthvalueTestCase
from .equal import TorchTensorEqualTestCase
from .scatter import TorchTensorScatterTestCase
from .bitwise_xor import TorchTensorBitwisexorTestCase
from .is_complex import TorchTensorIscomplexTestCase
from .istft import TorchTensorIstftTestCase
from .logical_not_ import TorchTensorLogicalnotTestCase
from .arctan2 import TorchTensorArctan2TestCase
from .sigmoid_ import TorchTensorSigmoidTestCase
from .sqrt_ import TorchTensorSqrtTestCase
from .allclose import TorchTensorAllcloseTestCase
from .record_stream import TorchTensorRecordstreamTestCase
from .pow import TorchTensorPowTestCase
from .copysign import TorchTensorCopysignTestCase
from .logical_or import TorchTensorLogicalorTestCase
from .index_reduce_ import TorchTensorIndexreduceTestCase
from .dense_dim import TorchTensorDensedimTestCase
from .isnan import TorchTensorIsnanTestCase
from .det import TorchTensorDetTestCase
from .isneginf import TorchTensorIsneginfTestCase
from .sgn import TorchTensorSgnTestCase
from .hypot import TorchTensorHypotTestCase
from .renorm import TorchTensorRenormTestCase
from .renorm_ import TorchTensorRenormTestCase
from .to_sparse_csr import TorchTensorTosparsecsrTestCase
from .arcsin_ import TorchTensorArcsinTestCase
from .apply_ import TorchTensorApplyTestCase
from .inner import TorchTensorInnerTestCase
from .log_normal_ import TorchTensorLognormalTestCase
from .ne_ import TorchTensorNeTestCase
from .addcmul_ import TorchTensorAddcmulTestCase
from .arccos_ import TorchTensorArccosTestCase
from .uniform_ import TorchTensorUniformTestCase
from .max import TorchTensorMaxTestCase
from .resize_as_ import TorchTensorResizeasTestCase
from .index_copy_ import TorchTensorIndexcopyTestCase
from .half import TorchTensorHalfTestCase
from .rsqrt import TorchTensorRsqrtTestCase
from .logcumsumexp import TorchTensorLogcumsumexpTestCase
from .indices import TorchTensorIndicesTestCase
from .addbmm import TorchTensorAddbmmTestCase
from .erfc import TorchTensorErfcTestCase
from .arcsin import TorchTensorArcsinTestCase
from .ndimension import TorchTensorNdimensionTestCase
from .tanh import TorchTensorTanhTestCase
from .ger import TorchTensorGerTestCase
from .multiply_ import TorchTensorMultiplyTestCase
from .smm import TorchTensorSmmTestCase
from .tanh_ import TorchTensorTanhTestCase
from .positive import TorchTensorPositiveTestCase
from .lerp import TorchTensorLerpTestCase
from .cholesky_inverse import TorchTensorCholeskyinverseTestCase
from .add import TorchTensorAddTestCase
from .view_as import TorchTensorViewasTestCase
from .sinh_ import TorchTensorSinhTestCase
from .is_quantized import TorchTensorIsquantizedTestCase
from .baddbmm import TorchTensorBaddbmmTestCase
from .nbytes import TorchTensorNbytesTestCase
from .cummin import TorchTensorCumminTestCase
from .maximum import TorchTensorMaximumTestCase
from .subtract import TorchTensorSubtractTestCase
from .dsplit import TorchTensorDsplitTestCase
from .fmod import TorchTensorFmodTestCase
from .to_sparse_bsr import TorchTensorTosparsebsrTestCase
from .scatter_add import TorchTensorScatteraddTestCase
from .neg import TorchTensorNegTestCase
from .slogdet import TorchTensorSlogdetTestCase
from .quantile import TorchTensorQuantileTestCase
from .log_ import TorchTensorLogTestCase
from .unsqueeze import TorchTensorUnsqueezeTestCase
from .squeeze_ import TorchTensorSqueezeTestCase
from .itemsize import TorchTensorItemsizeTestCase
from .addcmul import TorchTensorAddcmulTestCase
from .erf_ import TorchTensorErfTestCase
from .index_put_ import TorchTensorIndexputTestCase
from .matrix_power import TorchTensorMatrixpowerTestCase
from .logsumexp import TorchTensorLogsumexpTestCase
from .is_shared import TorchTensorIssharedTestCase
from .logical_or_ import TorchTensorLogicalorTestCase
from .narrow_copy import TorchTensorNarrowcopyTestCase
from .minimum import TorchTensorMinimumTestCase
from .resolve_conj import TorchTensorResolveconjTestCase
from .is_signed import TorchTensorIssignedTestCase
from .div import TorchTensorDivTestCase
from .bitwise_not import TorchTensorBitwisenotTestCase
from .qscheme import TorchTensorQschemeTestCase
from .bitwise_right_shift_ import TorchTensorBitwiserightshiftTestCase
from .logit import TorchTensorLogitTestCase
from .conj_physical_ import TorchTensorConjphysicalTestCase
from .trace import TorchTensorTraceTestCase
from .reciprocal import TorchTensorReciprocalTestCase
from .log import TorchTensorLogTestCase
from .asinh import TorchTensorAsinhTestCase
from .clamp_ import TorchTensorClampTestCase
from .copy_ import TorchTensorCopyTestCase
from .ge import TorchTensorGeTestCase
from .repeat import TorchTensorRepeatTestCase
from .cross import TorchTensorCrossTestCase
from .digamma_ import TorchTensorDigammaTestCase
from .argwhere import TorchTensorArgwhereTestCase
from .acosh import TorchTensorAcoshTestCase
from .addmv import TorchTensorAddmvTestCase
from .diagflat import TorchTensorDiagflatTestCase
from .trunc import TorchTensorTruncTestCase
from .scatter_ import TorchTensorScatterTestCase
from .sqrt import TorchTensorSqrtTestCase
from .heaviside import TorchTensorHeavisideTestCase
from .amin import TorchTensorAminTestCase
from .requires_grad import TorchTensorRequiresgradTestCase
from .sum import TorchTensorSumTestCase
from .dot import TorchTensorDotTestCase
from .moveaxis import TorchTensorMoveaxisTestCase
from .argmax import TorchTensorArgmaxTestCase
from .absolute_ import TorchTensorAbsoluteTestCase
from .divide import TorchTensorDivideTestCase
from .addcdiv_ import TorchTensorAddcdivTestCase
from .logaddexp import TorchTensorLogaddexpTestCase
from .hsplit import TorchTensorHsplitTestCase
from .digamma import TorchTensorDigammaTestCase
from .broadcast_to import TorchTensorBroadcasttoTestCase
from .chalf import TorchTensorChalfTestCase
from .is_conj import TorchTensorIsconjTestCase
from .reciprocal_ import TorchTensorReciprocalTestCase
from .sub_ import TorchTensorSubTestCase
from .log2 import TorchTensorLog2TestCase
from .log1p import TorchTensorLog1pTestCase
from .less import TorchTensorLessTestCase
from .atanh import TorchTensorAtanhTestCase
from .rsqrt_ import TorchTensorRsqrtTestCase
from .module_load import TorchTensorModuleloadTestCase
from .is_floating_point import TorchTensorIsfloatingpointTestCase
from .is_contiguous import TorchTensorIscontiguousTestCase
from .unique_consecutive import TorchTensorUniqueconsecutiveTestCase
from .prod import TorchTensorProdTestCase
from .detach import TorchTensorDetachTestCase
from .conj import TorchTensorConjTestCase
from .random_ import TorchTensorRandomTestCase
from .cosh import TorchTensorCoshTestCase
from .addbmm_ import TorchTensorAddbmmTestCase
from .long import TorchTensorLongTestCase
from .new_empty import TorchTensorNewemptyTestCase
from .fliplr import TorchTensorFliplrTestCase
from .t import TorchTensorTTestCase
from .register_hook import TorchTensorRegisterhookTestCase
from .clip import TorchTensorClipTestCase
from .ldexp_ import TorchTensorLdexpTestCase
from .greater_ import TorchTensorGreaterTestCase
from .index_copy import TorchTensorIndexcopyTestCase
from .isclose import TorchTensorIscloseTestCase
from .roll import TorchTensorRollTestCase
from .addmm import TorchTensorAddmmTestCase
from .mvlgamma_ import TorchTensorMvlgammaTestCase
from .xlogy_ import TorchTensorXlogyTestCase
from .le_ import TorchTensorLeTestCase
from .ndim import TorchTensorNdimTestCase
from .retains_grad import TorchTensorRetainsgradTestCase
from .remainder import TorchTensorRemainderTestCase
from .any import TorchTensorAnyTestCase
from .int_repr import TorchTensorIntreprTestCase
from .bitwise_xor_ import TorchTensorBitwisexorTestCase
from .fmax import TorchTensorFmaxTestCase
from .histogram import TorchTensorHistogramTestCase
from .unflatten import TorchTensorUnflattenTestCase
from .polygamma_ import TorchTensorPolygammaTestCase
from .bitwise_right_shift import TorchTensorBitwiserightshiftTestCase
from .sign import TorchTensorSignTestCase
from .clone import TorchTensorCloneTestCase
from .grad import TorchTensorGradTestCase
from .ormqr import TorchTensorOrmqrTestCase
from .dim import TorchTensorDimTestCase
from .sinh import TorchTensorSinhTestCase
from .select_scatter import TorchTensorSelectscatterTestCase
from .sparse_dim import TorchTensorSparsedimTestCase
from .is_set_to import TorchTensorIssettoTestCase
from .topk import TorchTensorTopkTestCase
from .masked_fill import TorchTensorMaskedfillTestCase
from .nanmean import TorchTensorNanmeanTestCase
from .repeat_interleave import TorchTensorRepeatinterleaveTestCase
from .is_meta import TorchTensorIsmetaTestCase
from .byte import TorchTensorByteTestCase
from .masked_fill_ import TorchTensorMaskedfillTestCase
from .int import TorchTensorIntTestCase
from .t_ import TorchTensorTTestCase
from .exponential_ import TorchTensorExponentialTestCase
from .negative_ import TorchTensorNegativeTestCase
from .cosh_ import TorchTensorCoshTestCase
from .corrcoef import TorchTensorCorrcoefTestCase
from .le import TorchTensorLeTestCase
from .add_ import TorchTensorAddTestCase
from .nan_to_num_ import TorchTensorNantonumTestCase
from .device import TorchTensorDeviceTestCase
from .numel import TorchTensorNumelTestCase
from .erfinv_ import TorchTensorErfinvTestCase
from .arctan_ import TorchTensorArctanTestCase
from .ravel import TorchTensorRavelTestCase
from .nanquantile import TorchTensorNanquantileTestCase
from .lcm_ import TorchTensorLcmTestCase
from .atan import TorchTensorAtanTestCase
from .unfold import TorchTensorUnfoldTestCase
from .logdet import TorchTensorLogdetTestCase
from .ceil_ import TorchTensorCeilTestCase
from .exp import TorchTensorExpTestCase
from .dist import TorchTensorDistTestCase
from .acos import TorchTensorAcosTestCase
from .logical_and import TorchTensorLogicalandTestCase
from .normal_ import TorchTensorNormalTestCase
from .true_divide import TorchTensorTruedivideTestCase
from .bitwise_left_shift_ import TorchTensorBitwiseleftshiftTestCase
from .detach_ import TorchTensorDetachTestCase
from .is_pinned import TorchTensorIspinnedTestCase
from .item import TorchTensorItemTestCase
from .bitwise_and_ import TorchTensorBitwiseandTestCase
from .less_equal import TorchTensorLessequalTestCase
from .ne import TorchTensorNeTestCase
from .unique import TorchTensorUniqueTestCase
from .short import TorchTensorShortTestCase
from .histc import TorchTensorHistcTestCase
from .not_equal_ import TorchTensorNotequalTestCase
from .lt_ import TorchTensorLtTestCase
from .lu_solve import TorchTensorLusolveTestCase
from .sinc_ import TorchTensorSincTestCase
from .as_subclass import TorchTensorAssubclassTestCase
from .nansum import TorchTensorNansumTestCase
from .sin import TorchTensorSinTestCase
from .hypot_ import TorchTensorHypotTestCase
from .new_full import TorchTensorNewfullTestCase
from .floor_ import TorchTensorFloorTestCase
from .nextafter_ import TorchTensorNextafterTestCase
from .reshape import TorchTensorReshapeTestCase
from .contiguous import TorchTensorContiguousTestCase
from .mul import TorchTensorMulTestCase
from .is_cuda import TorchTensorIscudaTestCase
from .adjoint import TorchTensorAdjointTestCase
from .lcm import TorchTensorLcmTestCase
from .new_ones import TorchTensorNewonesTestCase
from .less_equal_ import TorchTensorLessequalTestCase
from .flatten import TorchTensorFlattenTestCase
from .to_sparse_bsc import TorchTensorTosparsebscTestCase
from .slice_scatter import TorchTensorSlicescatterTestCase
from .mean import TorchTensorMeanTestCase
from .cauchy_ import TorchTensorCauchyTestCase
from .logical_xor_ import TorchTensorLogicalxorTestCase
from .sin_ import TorchTensorSinTestCase
from .backward import TorchTensorBackwardTestCase
from .q_per_channel_scales import TorchTensorQperchannelscalesTestCase
from .gt_ import TorchTensorGtTestCase
from .addmm_ import TorchTensorAddmmTestCase
from .mode import TorchTensorModeTestCase
from .register_post_accumulate_grad_hook import TorchTensorRegisterpostaccumulategradhookTestCase
from .expm1 import TorchTensorExpm1TestCase
from .to_dense import TorchTensorTodenseTestCase
from .acosh_ import TorchTensorAcoshTestCase
from .frac_ import TorchTensorFracTestCase
from .pin_memory import TorchTensorPinmemoryTestCase
from .signbit import TorchTensorSignbitTestCase
from .resize_ import TorchTensorResizeTestCase
from .masked_select import TorchTensorMaskedselectTestCase
from .cos_ import TorchTensorCosTestCase
from .vdot import TorchTensorVdotTestCase
from .stft import TorchTensorStftTestCase
from .var import TorchTensorVarTestCase
from .values import TorchTensorValuesTestCase
from .index_fill import TorchTensorIndexfillTestCase
from .put_ import TorchTensorPutTestCase
from .subtract_ import TorchTensorSubtractTestCase
from .isposinf import TorchTensorIsposinfTestCase
from .min import TorchTensorMinTestCase
from .q_per_channel_zero_points import TorchTensorQperchannelzeropointsTestCase
from .log2_ import TorchTensorLog2TestCase
from .atan_ import TorchTensorAtanTestCase
from .igamma_ import TorchTensorIgammaTestCase
from .imag import TorchTensorImagTestCase
from .pinverse import TorchTensorPinverseTestCase
from .view import TorchTensorViewTestCase
from .narrow import TorchTensorNarrowTestCase
from .rad2deg import TorchTensorRad2degTestCase
from .aminmax import TorchTensorAminmaxTestCase
from .as_strided import TorchTensorAsstridedTestCase
from .cuda import TorchTensorCudaTestCase
from .bitwise_or_ import TorchTensorBitwiseorTestCase
from .sspaddmm import TorchTensorSspaddmmTestCase
from .tensor_split import TorchTensorTensorsplitTestCase
from .tolist import TorchTensorTolistTestCase
from .logical_not import TorchTensorLogicalnotTestCase
from .isreal import TorchTensorIsrealTestCase
from .unbind import TorchTensorUnbindTestCase
from .nonzero import TorchTensorNonzeroTestCase
from .swapdims import TorchTensorSwapdimsTestCase
from .count_nonzero import TorchTensorCountnonzeroTestCase
from .div_ import TorchTensorDivTestCase
from .element_size import TorchTensorElementsizeTestCase
from .addcdiv import TorchTensorAddcdivTestCase
from .shape import TorchTensorShapeTestCase
from .mv import TorchTensorMvTestCase
from .igamma import TorchTensorIgammaTestCase
from .orgqr import TorchTensorOrgqrTestCase
from .gt import TorchTensorGtTestCase
from .conj_physical import TorchTensorConjphysicalTestCase
from .bfloat16 import TorchTensorBfloat16TestCase
from .retain_grad import TorchTensorRetaingradTestCase
from .fill_diagonal_ import TorchTensorFilldiagonalTestCase
from .gcd_ import TorchTensorGcdTestCase
from .new_zeros import TorchTensorNewzerosTestCase
from .clip_ import TorchTensorClipTestCase
from .eq import TorchTensorEqTestCase
from .msort import TorchTensorMsortTestCase
from .arctanh_ import TorchTensorArctanhTestCase
from .storage_type import TorchTensorStoragetypeTestCase
from .data_ptr import TorchTensorDataptrTestCase
from .xlogy import TorchTensorXlogyTestCase
from .outer import TorchTensorOuterTestCase
from .logit_ import TorchTensorLogitTestCase
from .arcsinh_ import TorchTensorArcsinhTestCase
from .map_ import TorchTensorMapTestCase
from .cumsum_ import TorchTensorCumsumTestCase
from .sub import TorchTensorSubTestCase
from .transpose_ import TorchTensorTransposeTestCase
from .take import TorchTensorTakeTestCase
from .logical_xor import TorchTensorLogicalxorTestCase
from .ge_ import TorchTensorGeTestCase
from .float_power import TorchTensorFloatpowerTestCase
from .diag import TorchTensorDiagTestCase
from .cumprod_ import TorchTensorCumprodTestCase
from .swapaxes import TorchTensorSwapaxesTestCase
from .clamp import TorchTensorClampTestCase
from .logical_and_ import TorchTensorLogicalandTestCase
from .bincount import TorchTensorBincountTestCase
from .log10 import TorchTensorLog10TestCase
from .fix import TorchTensorFixTestCase
from .amax import TorchTensorAmaxTestCase
from .sinc import TorchTensorSincTestCase
from .square_ import TorchTensorSquareTestCase
from .masked_scatter_ import TorchTensorMaskedscatterTestCase
from .floor_divide import TorchTensorFloordivideTestCase
from .bitwise_or import TorchTensorBitwiseorTestCase
from .vsplit import TorchTensorVsplitTestCase
from .index_select import TorchTensorIndexselectTestCase
from .cholesky_solve import TorchTensorCholeskysolveTestCase
from .arctanh import TorchTensorArctanhTestCase
from .frexp import TorchTensorFrexpTestCase
from .bmm import TorchTensorBmmTestCase
from .nanmedian import TorchTensorNanmedianTestCase
from .is_inference import TorchTensorIsinferenceTestCase
from .q_zero_point import TorchTensorQzeropointTestCase
from .argsort import TorchTensorArgsortTestCase
from .polygamma import TorchTensorPolygammaTestCase
from .sign_ import TorchTensorSignTestCase
from .float_power_ import TorchTensorFloatpowerTestCase
from .permute import TorchTensorPermuteTestCase
from .round import TorchTensorRoundTestCase
from .nextafter import TorchTensorNextafterTestCase
from .tril_ import TorchTensorTrilTestCase
from .abs_ import TorchTensorAbsTestCase
from .diff import TorchTensorDiffTestCase
from .gather import TorchTensorGatherTestCase
from .geometric_ import TorchTensorGeometricTestCase
from .floor_divide_ import TorchTensorFloordivideTestCase
from .matmul import TorchTensorMatmulTestCase
from .nan_to_num import TorchTensorNantonumTestCase
from .zero_ import TorchTensorZeroTestCase
from .isfinite import TorchTensorIsfiniteTestCase
from .diag_embed import TorchTensorDiagembedTestCase
from .to_sparse_csc import TorchTensorTosparsecscTestCase
from .atan2_ import TorchTensorAtan2TestCase
from .cummax import TorchTensorCummaxTestCase
from .arccos import TorchTensorArccosTestCase
from .igammac import TorchTensorIgammacTestCase
from .multinomial import TorchTensorMultinomialTestCase
from .arctan import TorchTensorArctanTestCase
from .split import TorchTensorSplitTestCase
from .flip import TorchTensorFlipTestCase
