from .lt import TorchTensorLtTestCase
from .matrixexp import TorchTensorMatrixexpTestCase
from .arccosh import TorchTensorArccoshTestCase
from .indexreduce import TorchTensorIndexreduceTestCase
from .fmod import TorchTensorFmodTestCase
from .softmax import TorchTensorSoftmaxTestCase
from .tril import TorchTensorTrilTestCase
from .lgamma import TorchTensorLgammaTestCase
from .cumprod import TorchTensorCumprodTestCase
from .expand import TorchTensorExpandTestCase
from .ldexp import TorchTensorLdexpTestCase
from .fill import TorchTensorFillTestCase
from .sparsemask import TorchTensorSparsemaskTestCase
from .bitwiseand import TorchTensorBitwiseandTestCase
from .copysign import TorchTensorCopysignTestCase
from .mul import TorchTensorMulTestCase
from .expm1 import TorchTensorExpm1TestCase
from .absolute import TorchTensorAbsoluteTestCase
from .scatterreduce import TorchTensorScatterreduceTestCase
from .lerp import TorchTensorLerpTestCase
from .erfc import TorchTensorErfcTestCase
from .bool import TorchTensorBoolTestCase
from .asinh import TorchTensorAsinhTestCase
from .igammac import TorchTensorIgammacTestCase
from .storageoffset import TorchTensorStorageoffsetTestCase
from .to import TorchTensorToTestCase
from .atanh import TorchTensorAtanhTestCase
from .asin import TorchTensorAsinTestCase
from .deg2rad import TorchTensorDeg2radTestCase
from .arcsinh import TorchTensorArcsinhTestCase
from .numpy import TorchTensorNumpyTestCase
from .floor import TorchTensorFloorTestCase
from .fmin import TorchTensorFminTestCase
from .sort import TorchTensorSortTestCase
from .reshapeas import TorchTensorReshapeasTestCase
from .indexput import TorchTensorIndexputTestCase
from .unsqueeze import TorchTensorUnsqueezeTestCase
from .cpu import TorchTensorCpuTestCase
from .bitwisenot import TorchTensorBitwisenotTestCase
from .untypedstorage import TorchTensorUntypedstorageTestCase
from .qr import TorchTensorQrTestCase
from .baddbmm import TorchTensorBaddbmmTestCase
from .arctan2 import TorchTensorArctan2TestCase
from .char import TorchTensorCharTestCase
from .indexadd import TorchTensorIndexaddTestCase
from .scatteradd import TorchTensorScatteraddTestCase
from .multiply import TorchTensorMultiplyTestCase
from .argmin import TorchTensorArgminTestCase
from .takealongdim import TorchTensorTakealongdimTestCase
from .norm import TorchTensorNormTestCase
from .greaterequal import TorchTensorGreaterequalTestCase
from .bernoulli import TorchTensorBernoulliTestCase
from .isleaf import TorchTensorIsleafTestCase
from .tosparse import TorchTensorTosparseTestCase
from .triu import TorchTensorTriuTestCase
from .qscale import TorchTensorQscaleTestCase
from .gcd import TorchTensorGcdTestCase
from .sgn import TorchTensorSgnTestCase
from .cdouble import TorchTensorCdoubleTestCase
from .tan import TorchTensorTanTestCase
from .chunk import TorchTensorChunkTestCase
from .sumtosize import TorchTensorSumtosizeTestCase
from .diagonalscatter import TorchTensorDiagonalscatterTestCase
from .greaterequal import TorchTensorGreaterequalTestCase
from .hardshrink import TorchTensorHardshrinkTestCase
from .negative import TorchTensorNegativeTestCase
from .cos import TorchTensorCosTestCase
from .qperchannelaxis import TorchTensorQperchannelaxisTestCase
from .acos import TorchTensorAcosTestCase
from .bitwiseleftshift import TorchTensorBitwiseleftshiftTestCase
from .addr import TorchTensorAddrTestCase
from .requiresgrad import TorchTensorRequiresgradTestCase
from .double import TorchTensorDoubleTestCase
from .stride import TorchTensorStrideTestCase
from .float import TorchTensorFloatTestCase
from .sharememory import TorchTensorSharememoryTestCase
from .erf import TorchTensorErfTestCase
from .greater import TorchTensorGreaterTestCase
from .square import TorchTensorSquareTestCase
from .flipud import TorchTensorFlipudTestCase
from .log10 import TorchTensorLog10TestCase
from .cumsum import TorchTensorCumsumTestCase
from .logaddexp2 import TorchTensorLogaddexp2TestCase
from .select import TorchTensorSelectTestCase
from .arccosh import TorchTensorArccoshTestCase
from .less import TorchTensorLessTestCase
from .lgamma import TorchTensorLgammaTestCase
from .angle import TorchTensorAngleTestCase
from .i0 import TorchTensorI0TestCase
from .truedivide import TorchTensorTruedivideTestCase
from .std import TorchTensorStdTestCase
from .diagonal import TorchTensorDiagonalTestCase
from .fix import TorchTensorFixTestCase
from .notequal import TorchTensorNotequalTestCase
from .cfloat import TorchTensorCfloatTestCase
from .indexfill import TorchTensorIndexfillTestCase
from .log1p import TorchTensorLog1pTestCase
from .typeas import TorchTensorTypeasTestCase
from .set import TorchTensorSetTestCase
from .mvlgamma import TorchTensorMvlgammaTestCase
from .real import TorchTensorRealTestCase
from .remainder import TorchTensorRemainderTestCase
from .newtensor import TorchTensorNewtensorTestCase
from .maskedscatter import TorchTensorMaskedscatterTestCase
from .geqrf import TorchTensorGeqrfTestCase
from .abs import TorchTensorAbsTestCase
from .rot90 import TorchTensorRot90TestCase
from .asin import TorchTensorAsinTestCase
from .addr import TorchTensorAddrTestCase
from .lu import TorchTensorLuTestCase
from .getdevice import TorchTensorGetdeviceTestCase
from .pow import TorchTensorPowTestCase
from .neg import TorchTensorNegTestCase
from .where import TorchTensorWhereTestCase
from .triangularsolve import TorchTensorTriangularsolveTestCase
from .mm import TorchTensorMmTestCase
from .type import TorchTensorTypeTestCase
from .sigmoid import TorchTensorSigmoidTestCase
from .atan2 import TorchTensorAtan2TestCase
from .inverse import TorchTensorInverseTestCase
from .addmv import TorchTensorAddmvTestCase
from .svd import TorchTensorSvdTestCase
from .squeeze import TorchTensorSqueezeTestCase
from .erfinv import TorchTensorErfinvTestCase
from .size import TorchTensorSizeTestCase
from .trunc import TorchTensorTruncTestCase
from .eq import TorchTensorEqTestCase
from .indexadd import TorchTensorIndexaddTestCase
from .resolveneg import TorchTensorResolvenegTestCase
from .tan import TorchTensorTanTestCase
from .dequantize import TorchTensorDequantizeTestCase
from .frac import TorchTensorFracTestCase
from .cholesky import TorchTensorCholeskyTestCase
from .cov import TorchTensorCovTestCase
from .ceil import TorchTensorCeilTestCase
from .triu import TorchTensorTriuTestCase
from .exp import TorchTensorExpTestCase
from .all import TorchTensorAllTestCase
from .tomkldnn import TorchTensorTomkldnnTestCase
from .divide import TorchTensorDivideTestCase
from .i0 import TorchTensorI0TestCase
from .issparse import TorchTensorIssparseTestCase
from .round import TorchTensorRoundTestCase
from .transpose import TorchTensorTransposeTestCase
from .movedim import TorchTensorMovedimTestCase
from .bernoulli import TorchTensorBernoulliTestCase
from .nelement import TorchTensorNelementTestCase
from .storage import TorchTensorStorageTestCase
from .dimorder import TorchTensorDimorderTestCase
from .median import TorchTensorMedianTestCase
from .tile import TorchTensorTileTestCase
from .expandas import TorchTensorExpandasTestCase
from .isinf import TorchTensorIsinfTestCase
from .scatterreduce import TorchTensorScatterreduceTestCase
from .kthvalue import TorchTensorKthvalueTestCase
from .equal import TorchTensorEqualTestCase
from .scatter import TorchTensorScatterTestCase
from .bitwisexor import TorchTensorBitwisexorTestCase
from .iscomplex import TorchTensorIscomplexTestCase
from .istft import TorchTensorIstftTestCase
from .logicalnot import TorchTensorLogicalnotTestCase
from .arctan2 import TorchTensorArctan2TestCase
from .sigmoid import TorchTensorSigmoidTestCase
from .sqrt import TorchTensorSqrtTestCase
from .allclose import TorchTensorAllcloseTestCase
from .recordstream import TorchTensorRecordstreamTestCase
from .pow import TorchTensorPowTestCase
from .copysign import TorchTensorCopysignTestCase
from .logicalor import TorchTensorLogicalorTestCase
from .indexreduce import TorchTensorIndexreduceTestCase
from .densedim import TorchTensorDensedimTestCase
from .isnan import TorchTensorIsnanTestCase
from .det import TorchTensorDetTestCase
from .isneginf import TorchTensorIsneginfTestCase
from .sgn import TorchTensorSgnTestCase
from .hypot import TorchTensorHypotTestCase
from .renorm import TorchTensorRenormTestCase
from .renorm import TorchTensorRenormTestCase
from .tosparsecsr import TorchTensorTosparsecsrTestCase
from .arcsin import TorchTensorArcsinTestCase
from .apply import TorchTensorApplyTestCase
from .inner import TorchTensorInnerTestCase
from .lognormal import TorchTensorLognormalTestCase
from .ne import TorchTensorNeTestCase
from .addcmul import TorchTensorAddcmulTestCase
from .arccos import TorchTensorArccosTestCase
from .uniform import TorchTensorUniformTestCase
from .max import TorchTensorMaxTestCase
from .resizeas import TorchTensorResizeasTestCase
from .indexcopy import TorchTensorIndexcopyTestCase
from .half import TorchTensorHalfTestCase
from .rsqrt import TorchTensorRsqrtTestCase
from .logcumsumexp import TorchTensorLogcumsumexpTestCase
from .indices import TorchTensorIndicesTestCase
from .addbmm import TorchTensorAddbmmTestCase
from .erfc import TorchTensorErfcTestCase
from .arcsin import TorchTensorArcsinTestCase
from .ndimension import TorchTensorNdimensionTestCase
from .tanh import TorchTensorTanhTestCase
from .ger import TorchTensorGerTestCase
from .multiply import TorchTensorMultiplyTestCase
from .smm import TorchTensorSmmTestCase
from .tanh import TorchTensorTanhTestCase
from .positive import TorchTensorPositiveTestCase
from .lerp import TorchTensorLerpTestCase
from .choleskyinverse import TorchTensorCholeskyinverseTestCase
from .add import TorchTensorAddTestCase
from .viewas import TorchTensorViewasTestCase
from .sinh import TorchTensorSinhTestCase
from .isquantized import TorchTensorIsquantizedTestCase
from .baddbmm import TorchTensorBaddbmmTestCase
from .nbytes import TorchTensorNbytesTestCase
from .cummin import TorchTensorCumminTestCase
from .maximum import TorchTensorMaximumTestCase
from .subtract import TorchTensorSubtractTestCase
from .dsplit import TorchTensorDsplitTestCase
from .fmod import TorchTensorFmodTestCase
from .tosparsebsr import TorchTensorTosparsebsrTestCase
from .scatteradd import TorchTensorScatteraddTestCase
from .neg import TorchTensorNegTestCase
from .slogdet import TorchTensorSlogdetTestCase
from .quantile import TorchTensorQuantileTestCase
from .log import TorchTensorLogTestCase
from .unsqueeze import TorchTensorUnsqueezeTestCase
from .squeeze import TorchTensorSqueezeTestCase
from .itemsize import TorchTensorItemsizeTestCase
from .addcmul import TorchTensorAddcmulTestCase
from .erf import TorchTensorErfTestCase
from .indexput import TorchTensorIndexputTestCase
from .matrixpower import TorchTensorMatrixpowerTestCase
from .logsumexp import TorchTensorLogsumexpTestCase
from .isshared import TorchTensorIssharedTestCase
from .logicalor import TorchTensorLogicalorTestCase
from .narrowcopy import TorchTensorNarrowcopyTestCase
from .minimum import TorchTensorMinimumTestCase
from .resolveconj import TorchTensorResolveconjTestCase
from .issigned import TorchTensorIssignedTestCase
from .div import TorchTensorDivTestCase
from .bitwisenot import TorchTensorBitwisenotTestCase
from .qscheme import TorchTensorQschemeTestCase
from .bitwiserightshift import TorchTensorBitwiserightshiftTestCase
from .logit import TorchTensorLogitTestCase
from .conjphysical import TorchTensorConjphysicalTestCase
from .trace import TorchTensorTraceTestCase
from .reciprocal import TorchTensorReciprocalTestCase
from .log import TorchTensorLogTestCase
from .asinh import TorchTensorAsinhTestCase
from .clamp import TorchTensorClampTestCase
from .copy import TorchTensorCopyTestCase
from .ge import TorchTensorGeTestCase
from .repeat import TorchTensorRepeatTestCase
from .cross import TorchTensorCrossTestCase
from .digamma import TorchTensorDigammaTestCase
from .argwhere import TorchTensorArgwhereTestCase
from .acosh import TorchTensorAcoshTestCase
from .addmv import TorchTensorAddmvTestCase
from .diagflat import TorchTensorDiagflatTestCase
from .trunc import TorchTensorTruncTestCase
from .scatter import TorchTensorScatterTestCase
from .sqrt import TorchTensorSqrtTestCase
from .heaviside import TorchTensorHeavisideTestCase
from .amin import TorchTensorAminTestCase
from .requiresgrad import TorchTensorRequiresgradTestCase
from .sum import TorchTensorSumTestCase
from .dot import TorchTensorDotTestCase
from .moveaxis import TorchTensorMoveaxisTestCase
from .argmax import TorchTensorArgmaxTestCase
from .absolute import TorchTensorAbsoluteTestCase
from .divide import TorchTensorDivideTestCase
from .addcdiv import TorchTensorAddcdivTestCase
from .logaddexp import TorchTensorLogaddexpTestCase
from .hsplit import TorchTensorHsplitTestCase
from .digamma import TorchTensorDigammaTestCase
from .broadcastto import TorchTensorBroadcasttoTestCase
from .chalf import TorchTensorChalfTestCase
from .isconj import TorchTensorIsconjTestCase
from .reciprocal import TorchTensorReciprocalTestCase
from .sub import TorchTensorSubTestCase
from .log2 import TorchTensorLog2TestCase
from .log1p import TorchTensorLog1pTestCase
from .less import TorchTensorLessTestCase
from .atanh import TorchTensorAtanhTestCase
from .rsqrt import TorchTensorRsqrtTestCase
from .moduleload import TorchTensorModuleloadTestCase
from .isfloatingpoint import TorchTensorIsfloatingpointTestCase
from .iscontiguous import TorchTensorIscontiguousTestCase
from .uniqueconsecutive import TorchTensorUniqueconsecutiveTestCase
from .prod import TorchTensorProdTestCase
from .detach import TorchTensorDetachTestCase
from .conj import TorchTensorConjTestCase
from .random import TorchTensorRandomTestCase
from .cosh import TorchTensorCoshTestCase
from .addbmm import TorchTensorAddbmmTestCase
from .long import TorchTensorLongTestCase
from .newempty import TorchTensorNewemptyTestCase
from .fliplr import TorchTensorFliplrTestCase
from .t import TorchTensorTTestCase
from .registerhook import TorchTensorRegisterhookTestCase
from .clip import TorchTensorClipTestCase
from .ldexp import TorchTensorLdexpTestCase
from .greater import TorchTensorGreaterTestCase
from .indexcopy import TorchTensorIndexcopyTestCase
from .isclose import TorchTensorIscloseTestCase
from .roll import TorchTensorRollTestCase
from .addmm import TorchTensorAddmmTestCase
from .mvlgamma import TorchTensorMvlgammaTestCase
from .xlogy import TorchTensorXlogyTestCase
from .le import TorchTensorLeTestCase
from .ndim import TorchTensorNdimTestCase
from .retainsgrad import TorchTensorRetainsgradTestCase
from .remainder import TorchTensorRemainderTestCase
from .any import TorchTensorAnyTestCase
from .intrepr import TorchTensorIntreprTestCase
from .bitwisexor import TorchTensorBitwisexorTestCase
from .fmax import TorchTensorFmaxTestCase
from .histogram import TorchTensorHistogramTestCase
from .unflatten import TorchTensorUnflattenTestCase
from .polygamma import TorchTensorPolygammaTestCase
from .bitwiserightshift import TorchTensorBitwiserightshiftTestCase
from .sign import TorchTensorSignTestCase
from .clone import TorchTensorCloneTestCase
from .grad import TorchTensorGradTestCase
from .ormqr import TorchTensorOrmqrTestCase
from .dim import TorchTensorDimTestCase
from .sinh import TorchTensorSinhTestCase
from .selectscatter import TorchTensorSelectscatterTestCase
from .sparsedim import TorchTensorSparsedimTestCase
from .issetto import TorchTensorIssettoTestCase
from .topk import TorchTensorTopkTestCase
from .maskedfill import TorchTensorMaskedfillTestCase
from .nanmean import TorchTensorNanmeanTestCase
from .repeatinterleave import TorchTensorRepeatinterleaveTestCase
from .ismeta import TorchTensorIsmetaTestCase
from .byte import TorchTensorByteTestCase
from .maskedfill import TorchTensorMaskedfillTestCase
from .int import TorchTensorIntTestCase
from .t import TorchTensorTTestCase
from .exponential import TorchTensorExponentialTestCase
from .negative import TorchTensorNegativeTestCase
from .cosh import TorchTensorCoshTestCase
from .corrcoef import TorchTensorCorrcoefTestCase
from .le import TorchTensorLeTestCase
from .add import TorchTensorAddTestCase
from .nantonum import TorchTensorNantonumTestCase
from .device import TorchTensorDeviceTestCase
from .numel import TorchTensorNumelTestCase
from .erfinv import TorchTensorErfinvTestCase
from .arctan import TorchTensorArctanTestCase
from .ravel import TorchTensorRavelTestCase
from .nanquantile import TorchTensorNanquantileTestCase
from .lcm import TorchTensorLcmTestCase
from .atan import TorchTensorAtanTestCase
from .unfold import TorchTensorUnfoldTestCase
from .logdet import TorchTensorLogdetTestCase
from .ceil import TorchTensorCeilTestCase
from .exp import TorchTensorExpTestCase
from .dist import TorchTensorDistTestCase
from .acos import TorchTensorAcosTestCase
from .logicaland import TorchTensorLogicalandTestCase
from .normal import TorchTensorNormalTestCase
from .truedivide import TorchTensorTruedivideTestCase
from .bitwiseleftshift import TorchTensorBitwiseleftshiftTestCase
from .detach import TorchTensorDetachTestCase
from .ispinned import TorchTensorIspinnedTestCase
from .item import TorchTensorItemTestCase
from .bitwiseand import TorchTensorBitwiseandTestCase
from .lessequal import TorchTensorLessequalTestCase
from .ne import TorchTensorNeTestCase
from .unique import TorchTensorUniqueTestCase
from .short import TorchTensorShortTestCase
from .histc import TorchTensorHistcTestCase
from .notequal import TorchTensorNotequalTestCase
from .lt import TorchTensorLtTestCase
from .lusolve import TorchTensorLusolveTestCase
from .sinc import TorchTensorSincTestCase
from .assubclass import TorchTensorAssubclassTestCase
from .nansum import TorchTensorNansumTestCase
from .sin import TorchTensorSinTestCase
from .hypot import TorchTensorHypotTestCase
from .newfull import TorchTensorNewfullTestCase
from .floor import TorchTensorFloorTestCase
from .nextafter import TorchTensorNextafterTestCase
from .reshape import TorchTensorReshapeTestCase
from .contiguous import TorchTensorContiguousTestCase
from .mul import TorchTensorMulTestCase
from .iscuda import TorchTensorIscudaTestCase
from .adjoint import TorchTensorAdjointTestCase
from .lcm import TorchTensorLcmTestCase
from .newones import TorchTensorNewonesTestCase
from .lessequal import TorchTensorLessequalTestCase
from .flatten import TorchTensorFlattenTestCase
from .tosparsebsc import TorchTensorTosparsebscTestCase
from .slicescatter import TorchTensorSlicescatterTestCase
from .mean import TorchTensorMeanTestCase
from .cauchy import TorchTensorCauchyTestCase
from .logicalxor import TorchTensorLogicalxorTestCase
from .sin import TorchTensorSinTestCase
from .backward import TorchTensorBackwardTestCase
from .qperchannelscales import TorchTensorQperchannelscalesTestCase
from .gt import TorchTensorGtTestCase
from .addmm import TorchTensorAddmmTestCase
from .mode import TorchTensorModeTestCase
from .registerpostaccumulategradhook import TorchTensorRegisterpostaccumulategradhookTestCase
from .expm1 import TorchTensorExpm1TestCase
from .todense import TorchTensorTodenseTestCase
from .acosh import TorchTensorAcoshTestCase
from .frac import TorchTensorFracTestCase
from .pinmemory import TorchTensorPinmemoryTestCase
from .signbit import TorchTensorSignbitTestCase
from .resize import TorchTensorResizeTestCase
from .maskedselect import TorchTensorMaskedselectTestCase
from .cos import TorchTensorCosTestCase
from .vdot import TorchTensorVdotTestCase
from .stft import TorchTensorStftTestCase
from .var import TorchTensorVarTestCase
from .values import TorchTensorValuesTestCase
from .indexfill import TorchTensorIndexfillTestCase
from .put import TorchTensorPutTestCase
from .subtract import TorchTensorSubtractTestCase
from .isposinf import TorchTensorIsposinfTestCase
from .min import TorchTensorMinTestCase
from .qperchannelzeropoints import TorchTensorQperchannelzeropointsTestCase
from .log2 import TorchTensorLog2TestCase
from .atan import TorchTensorAtanTestCase
from .igamma import TorchTensorIgammaTestCase
from .imag import TorchTensorImagTestCase
from .pinverse import TorchTensorPinverseTestCase
from .view import TorchTensorViewTestCase
from .narrow import TorchTensorNarrowTestCase
from .rad2deg import TorchTensorRad2degTestCase
from .aminmax import TorchTensorAminmaxTestCase
from .asstrided import TorchTensorAsstridedTestCase
from .cuda import TorchTensorCudaTestCase
from .bitwiseor import TorchTensorBitwiseorTestCase
from .sspaddmm import TorchTensorSspaddmmTestCase
from .tensorsplit import TorchTensorTensorsplitTestCase
from .tolist import TorchTensorTolistTestCase
from .logicalnot import TorchTensorLogicalnotTestCase
from .isreal import TorchTensorIsrealTestCase
from .unbind import TorchTensorUnbindTestCase
from .nonzero import TorchTensorNonzeroTestCase
from .swapdims import TorchTensorSwapdimsTestCase
from .countnonzero import TorchTensorCountnonzeroTestCase
from .div import TorchTensorDivTestCase
from .elementsize import TorchTensorElementsizeTestCase
from .addcdiv import TorchTensorAddcdivTestCase
from .shape import TorchTensorShapeTestCase
from .mv import TorchTensorMvTestCase
from .igamma import TorchTensorIgammaTestCase
from .orgqr import TorchTensorOrgqrTestCase
from .gt import TorchTensorGtTestCase
from .conjphysical import TorchTensorConjphysicalTestCase
from .bfloat16 import TorchTensorBfloat16TestCase
from .retaingrad import TorchTensorRetaingradTestCase
from .filldiagonal import TorchTensorFilldiagonalTestCase
from .gcd import TorchTensorGcdTestCase
from .newzeros import TorchTensorNewzerosTestCase
from .clip import TorchTensorClipTestCase
from .eq import TorchTensorEqTestCase
from .msort import TorchTensorMsortTestCase
from .arctanh import TorchTensorArctanhTestCase
from .storagetype import TorchTensorStoragetypeTestCase
from .dataptr import TorchTensorDataptrTestCase
from .xlogy import TorchTensorXlogyTestCase
from .outer import TorchTensorOuterTestCase
from .logit import TorchTensorLogitTestCase
from .arcsinh import TorchTensorArcsinhTestCase
from .map import TorchTensorMapTestCase
from .cumsum import TorchTensorCumsumTestCase
from .sub import TorchTensorSubTestCase
from .transpose import TorchTensorTransposeTestCase
from .take import TorchTensorTakeTestCase
from .logicalxor import TorchTensorLogicalxorTestCase
from .ge import TorchTensorGeTestCase
from .floatpower import TorchTensorFloatpowerTestCase
from .diag import TorchTensorDiagTestCase
from .cumprod import TorchTensorCumprodTestCase
from .swapaxes import TorchTensorSwapaxesTestCase
from .clamp import TorchTensorClampTestCase
from .logicaland import TorchTensorLogicalandTestCase
from .bincount import TorchTensorBincountTestCase
from .log10 import TorchTensorLog10TestCase
from .fix import TorchTensorFixTestCase
from .amax import TorchTensorAmaxTestCase
from .sinc import TorchTensorSincTestCase
from .square import TorchTensorSquareTestCase
from .maskedscatter import TorchTensorMaskedscatterTestCase
from .floordivide import TorchTensorFloordivideTestCase
from .bitwiseor import TorchTensorBitwiseorTestCase
from .vsplit import TorchTensorVsplitTestCase
from .indexselect import TorchTensorIndexselectTestCase
from .choleskysolve import TorchTensorCholeskysolveTestCase
from .arctanh import TorchTensorArctanhTestCase
from .frexp import TorchTensorFrexpTestCase
from .bmm import TorchTensorBmmTestCase
from .nanmedian import TorchTensorNanmedianTestCase
from .isinference import TorchTensorIsinferenceTestCase
from .qzeropoint import TorchTensorQzeropointTestCase
from .argsort import TorchTensorArgsortTestCase
from .polygamma import TorchTensorPolygammaTestCase
from .sign import TorchTensorSignTestCase
from .floatpower import TorchTensorFloatpowerTestCase
from .permute import TorchTensorPermuteTestCase
from .round import TorchTensorRoundTestCase
from .nextafter import TorchTensorNextafterTestCase
from .tril import TorchTensorTrilTestCase
from .abs import TorchTensorAbsTestCase
from .diff import TorchTensorDiffTestCase
from .gather import TorchTensorGatherTestCase
from .geometric import TorchTensorGeometricTestCase
from .floordivide import TorchTensorFloordivideTestCase
from .matmul import TorchTensorMatmulTestCase
from .nantonum import TorchTensorNantonumTestCase
from .zero import TorchTensorZeroTestCase
from .isfinite import TorchTensorIsfiniteTestCase
from .diagembed import TorchTensorDiagembedTestCase
from .tosparsecsc import TorchTensorTosparsecscTestCase
from .atan2 import TorchTensorAtan2TestCase
from .cummax import TorchTensorCummaxTestCase
from .arccos import TorchTensorArccosTestCase
from .igammac import TorchTensorIgammacTestCase
from .multinomial import TorchTensorMultinomialTestCase
from .arctan import TorchTensorArctanTestCase
from .split import TorchTensorSplitTestCase
from .flip import TorchTensorFlipTestCase
