from .InputKind import TorchExportGraphsignatureInputkindTestCase
from .get_replace_hook import TorchExportGraphsignatureGetreplacehookTestCase
from .InputSpec import TorchExportGraphsignatureInputspecTestCase
from .ExportGraphSignature import TorchExportGraphsignatureExportgraphsignatureTestCase
from .OutputKind import TorchExportGraphsignatureOutputkindTestCase
from .CustomObjArgument import TorchExportGraphsignatureCustomobjargumentTestCase
from .OutputSpec import TorchExportGraphsignatureOutputspecTestCase
from .replace_all_uses import TorchExportGraphsignatureReplaceallusesTestCase
