from .is_available import TorchCpuIsavailableTestCase
from .synchronize import TorchCpuSynchronizeTestCase
from .device_count import TorchCpuDevicecountTestCase
from .stream import TorchCpuStreamTestCase
from .StreamContext import TorchCpuStreamcontextTestCase
from .current_device import TorchCpuCurrentdeviceTestCase
from .current_stream import TorchCpuCurrentstreamTestCase
from .set_device import TorchCpuSetdeviceTestCase
