from .isin import TorchIsinTestCase
from .unique import TorchUniqueTestCase
from .isposinf import TorchIsposinfTestCase
from .kron import TorchKronTestCase
from .result_type import TorchResulttypeTestCase
from .enable_grad import TorchEnablegradTestCase
from .stft import TorchStftTestCase
from .full import TorchFullTestCase
from .vdot import TorchVdotTestCase
from .hstack import TorchHstackTestCase
from .broadcast_shapes import TorchBroadcastshapesTestCase
from .mean import TorchMeanTestCase
from .orgqr import TorchOrgqrTestCase
from .hann_window import TorchHannwindowTestCase
from .rand import TorchRandTestCase
from .get_num_interop_threads import TorchGetnuminteropthreadsTestCase
from .cond import TorchCondTestCase
from .nansum import TorchNansumTestCase
from .mode import TorchModeTestCase
from .bucketize import TorchBucketizeTestCase
from .dot import TorchDotTestCase
from .sum import TorchSumTestCase
from ._foreach_log import TorchForeachlogTestCase
from .floor_divide import TorchFloordivideTestCase
from .exp2 import TorchExp2TestCase
from ._foreach_sqrt_ import TorchForeachsqrtTestCase
from .expm1 import TorchExpm1TestCase
from ._foreach_neg import TorchForeachnegTestCase
from .index_select import TorchIndexselectTestCase
from .stack import TorchStackTestCase
from .bitwise_and import TorchBitwiseandTestCase
from ._foreach_asin import TorchForeachasinTestCase
from .bitwise_or import TorchBitwiseorTestCase
from .are_deterministic_algorithms_enabled import TorchAredeterministicalgorithmsenabledTestCase
from .swapdims import TorchSwapdimsTestCase
from .is_deterministic_algorithms_warn_only_enabled import TorchIsdeterministicalgorithmswarnonlyenabledTestCase
from .einsum import TorchEinsumTestCase
from .movedim import TorchMovedimTestCase
from .any import TorchAnyTestCase
from .logdet import TorchLogdetTestCase
from .imag import TorchImagTestCase

import torch
if torch.__version__ >= "2.3.0":
    from .get_default_device import TorchGetdefaultdeviceTestCase
from .diag_embed import TorchDiagembedTestCase
from .is_inference_mode_enabled import TorchIsinferencemodeenabledTestCase
from .ge import TorchGeTestCase
from .arctan2 import TorchArctan2TestCase
from .compiled_with_cxx11_abi import TorchCompiledwithcxx11abiTestCase
from .compile import TorchCompileTestCase
from .set_default_tensor_type import TorchSetdefaulttensortypeTestCase
from .seed import TorchSeedTestCase
from .normal import TorchNormalTestCase
from .pinverse import TorchPinverseTestCase
from .scatter import TorchScatterTestCase
from .lobpcg import TorchLobpcgTestCase
from .nan_to_num import TorchNantonumTestCase
from ._foreach_exp_ import TorchForeachexpTestCase
from .sinc import TorchSincTestCase
from .amax import TorchAmaxTestCase
from .round import TorchRoundTestCase
from .nanmedian import TorchNanmedianTestCase
from .svd_lowrank import TorchSvdlowrankTestCase
from .exp import TorchExpTestCase
from ._foreach_ceil import TorchForeachceilTestCase
from ._foreach_tan_ import TorchForeachtanTestCase
from .swapaxes import TorchSwapaxesTestCase
from .polygamma import TorchPolygammaTestCase
from ._foreach_frac import TorchForeachfracTestCase
from ._foreach_trunc import TorchForeachtruncTestCase
from .set_num_interop_threads import TorchSetnuminteropthreadsTestCase
from .minimum import TorchMinimumTestCase
from .bincount import TorchBincountTestCase
from .fliplr import TorchFliplrTestCase
from .nextafter import TorchNextafterTestCase
from .frexp import TorchFrexpTestCase
from .split import TorchSplitTestCase
from .triu_indices import TorchTriuindicesTestCase
from .export import TorchExportTestCase
from .view_as_complex import TorchViewascomplexTestCase
from .resolve_neg import TorchResolvenegTestCase
from .diag import TorchDiagTestCase
from .take import TorchTakeTestCase
from .i0 import TorchI0TestCase
from ._foreach_neg_ import TorchForeachnegTestCase
from .isfinite import TorchIsfiniteTestCase
from .select_scatter import TorchSelectscatterTestCase
from .sin import TorchSinTestCase
from .empty_like import TorchEmptylikeTestCase
from .meshgrid import TorchMeshgridTestCase
from .baddbmm import TorchBaddbmmTestCase
from .diff import TorchDiffTestCase
from .set_default_device import TorchSetdefaultdeviceTestCase
from .hsplit import TorchHsplitTestCase
from .as_strided import TorchAsstridedTestCase
from .manual_seed import TorchManualseedTestCase
from .argmax import TorchArgmaxTestCase
from .flip import TorchFlipTestCase
from .msort import TorchMsortTestCase
from ._assert import TorchAssertTestCase
from .xlogy import TorchXlogyTestCase
from .outer import TorchOuterTestCase
from .divide import TorchDivideTestCase
from .hamming_window import TorchHammingwindowTestCase
from .unravel_index import TorchUnravelindexTestCase
from .set_printoptions import TorchSetprintoptionsTestCase
from .tensor_split import TorchTensorsplitTestCase
from ._foreach_sinh_ import TorchForeachsinhTestCase
from .zeros_like import TorchZeroslikeTestCase
from .addcmul import TorchAddcmulTestCase
from .get_rng_state import TorchGetrngstateTestCase
from .maximum import TorchMaximumTestCase
from .log10 import TorchLog10TestCase
from .slogdet import TorchSlogdetTestCase
from .clamp import TorchClampTestCase
from .addmm import TorchAddmmTestCase
from .less import TorchLessTestCase
from .var import TorchVarTestCase
from ._foreach_erfc import TorchForeacherfcTestCase
from .min import TorchMinTestCase
from .empty_strided import TorchEmptystridedTestCase
from .log2 import TorchLog2TestCase
from ._foreach_lgamma_ import TorchForeachlgammaTestCase
from .prod import TorchProdTestCase
from .vsplit import TorchVsplitTestCase
from .remainder import TorchRemainderTestCase
from .ormqr import TorchOrmqrTestCase
from .arctan import TorchArctanTestCase
from .unflatten import TorchUnflattenTestCase
from .histogram import TorchHistogramTestCase
from .clone import TorchCloneTestCase
from .vmap import TorchVmapTestCase
from .cummax import TorchCummaxTestCase
from .arccos import TorchArccosTestCase
from .lcm import TorchLcmTestCase
from .set_default_dtype import TorchSetdefaultdtypeTestCase
from .mul import TorchMulTestCase
from .matmul import TorchMatmulTestCase
from .var_mean import TorchVarmeanTestCase
from .moveaxis import TorchMoveaxisTestCase
from .gather import TorchGatherTestCase
from .fmax import TorchFmaxTestCase
from ._foreach_floor import TorchForeachfloorTestCase
from ._foreach_floor_ import TorchForeachfloorTestCase
from .sym_max import TorchSymmaxTestCase
from .less_equal import TorchLessequalTestCase
from .bartlett_window import TorchBartlettwindowTestCase
from ._foreach_erfc_ import TorchForeacherfcTestCase
from .arccosh import TorchArccoshTestCase
from .rand_like import TorchRandlikeTestCase
from .topk import TorchTopkTestCase
from .logaddexp import TorchLogaddexpTestCase
from ._foreach_abs import TorchForeachabsTestCase
from .complex import TorchComplexTestCase
from .softmax import TorchSoftmaxTestCase
from .sinh import TorchSinhTestCase
from .cumprod import TorchCumprodTestCase
from .sign import TorchSignTestCase
from .fake_quantize_per_channel_affine import TorchFakequantizeperchannelaffineTestCase
from .tril_indices import TorchTrilindicesTestCase
from .deg2rad import TorchDeg2radTestCase
from .clip import TorchClipTestCase
from .bitwise_xor import TorchBitwisexorTestCase
from .cosh import TorchCoshTestCase
from .load import TorchLoadTestCase
from .ones_like import TorchOneslikeTestCase
from .arcsinh import TorchArcsinhTestCase
from .conj import TorchConjTestCase
from .greater_equal import TorchGreaterequalTestCase
from .blackman_window import TorchBlackmanwindowTestCase
from .fake_quantize_per_tensor_affine import TorchFakequantizepertensoraffineTestCase
from .lu import TorchLuTestCase
from .atanh import TorchAtanhTestCase
from .cumulative_trapezoid import TorchCumulativetrapezoidTestCase
from .mm import TorchMmTestCase
from .quantize_per_channel import TorchQuantizeperchannelTestCase
from .roll import TorchRollTestCase
from .log1p import TorchLog1pTestCase
from ._foreach_erf import TorchForeacherfTestCase
from .cholesky_solve import TorchCholeskysolveTestCase
from .is_warn_always_enabled import TorchIswarnalwaysenabledTestCase
from .sigmoid import TorchSigmoidTestCase
from .histc import TorchHistcTestCase
from .inverse import TorchInverseTestCase
from .narrow import TorchNarrowTestCase
from .trapz import TorchTrapzTestCase
from ._foreach_sqrt import TorchForeachsqrtTestCase
from .squeeze import TorchSqueezeTestCase
from .concat import TorchConcatTestCase
from .searchsorted import TorchSearchsortedTestCase
from .dist import TorchDistTestCase
from .narrow_copy import TorchNarrowcopyTestCase
from .acos import TorchAcosTestCase
from ._foreach_cos import TorchForeachcosTestCase
from .bitwise_not import TorchBitwisenotTestCase
from .sparse_bsr_tensor import TorchSparsebsrtensorTestCase
from .bitwise_left_shift import TorchBitwiseleftshiftTestCase
from .sparse_coo_tensor import TorchSparsecootensorTestCase
from .atan import TorchAtanTestCase
from .broadcast_to import TorchBroadcasttoTestCase
from ._foreach_tan import TorchForeachtanTestCase
from .fix import TorchFixTestCase
from .igamma import TorchIgammaTestCase
from .sub import TorchSubTestCase
from .corrcoef import TorchCorrcoefTestCase
from .lt import TorchLtTestCase
from ._foreach_erf_ import TorchForeacherfTestCase
from .unbind import TorchUnbindTestCase
from .isreal import TorchIsrealTestCase
from .is_nonzero import TorchIsnonzeroTestCase
from .greater import TorchGreaterTestCase
from ._foreach_asin_ import TorchForeachasinTestCase
from .get_default_dtype import TorchGetdefaultdtypeTestCase
from .index_copy import TorchIndexcopyTestCase
from .from_numpy import TorchFromnumpyTestCase
from ._foreach_log_ import TorchForeachlogTestCase
from ._foreach_sigmoid import TorchForeachsigmoidTestCase
from ._foreach_sigmoid_ import TorchForeachsigmoidTestCase
from .lu_solve import TorchLusolveTestCase
from .sparse_csc_tensor import TorchSparsecsctensorTestCase
from .combinations import TorchCombinationsTestCase
from .ravel import TorchRavelTestCase
from .ones import TorchOnesTestCase
from .vstack import TorchVstackTestCase
from .scatter_add import TorchScatteraddTestCase
from .numel import TorchNumelTestCase
from .bmm import TorchBmmTestCase
from .qr import TorchQrTestCase
from ._foreach_acos_ import TorchForeachacosTestCase
from .inner import TorchInnerTestCase
from ._foreach_sinh import TorchForeachsinhTestCase
from .erfinv import TorchErfinvTestCase
from .aminmax import TorchAminmaxTestCase
from .tensordot import TorchTensordotTestCase
from .row_stack import TorchRowstackTestCase
from .masked_select import TorchMaskedselectTestCase
from .rad2deg import TorchRad2degTestCase
from .as_tensor import TorchAstensorTestCase
from .allclose import TorchAllcloseTestCase
from .isnan import TorchIsnanTestCase
from .initial_seed import TorchInitialseedTestCase
from .hypot import TorchHypotTestCase
from .randn import TorchRandnTestCase
from .kthvalue import TorchKthvalueTestCase
from .from_dlpack import TorchFromdlpackTestCase
from .addcdiv import TorchAddcdivTestCase
from .slice_scatter import TorchSlicescatterTestCase
from .set_num_threads import TorchSetnumthreadsTestCase
from .rsqrt import TorchRsqrtTestCase
from .lu_unpack import TorchLuunpackTestCase
from .view_as_real import TorchViewasrealTestCase
from .tile import TorchTileTestCase
from .get_num_threads import TorchGetnumthreadsTestCase
from .nonzero import TorchNonzeroTestCase
from .save import TorchSaveTestCase
from .cat import TorchCatTestCase
from .randn_like import TorchRandnlikeTestCase
from .eq import TorchEqTestCase
from ._foreach_cosh import TorchForeachcoshTestCase
from ._foreach_atan_ import TorchForeachatanTestCase
from .select import TorchSelectTestCase
from .resolve_conj import TorchResolveconjTestCase
from .tan import TorchTanTestCase
from .count_nonzero import TorchCountnonzeroTestCase
from ._foreach_log2_ import TorchForeachlog2TestCase
from .lgamma import TorchLgammaTestCase
from .reciprocal import TorchReciprocalTestCase
from .transpose import TorchTransposeTestCase
from .square import TorchSquareTestCase
from .concatenate import TorchConcatenateTestCase
from .cos import TorchCosTestCase
from .matrix_power import TorchMatrixpowerTestCase
from .asarray import TorchAsarrayTestCase
from .flipud import TorchFlipudTestCase
from .cumsum import TorchCumsumTestCase
from .adjoint import TorchAdjointTestCase
from .erfc import TorchErfcTestCase
from .conj_physical import TorchConjphysicalTestCase
from .flatten import TorchFlattenTestCase
from .eye import TorchEyeTestCase
from .gcd import TorchGcdTestCase
from ._foreach_frac_ import TorchForeachfracTestCase
from ._foreach_log2 import TorchForeachlog2TestCase
from .kaiser_window import TorchKaiserwindowTestCase
from ._foreach_expm1 import TorchForeachexpm1TestCase
from .zeros import TorchZerosTestCase
from .Generator import TorchGeneratorTestCase
from .istft import TorchIstftTestCase
from .histogramdd import TorchHistogramddTestCase
from .equal import TorchEqualTestCase
from .randint_like import TorchRandintlikeTestCase
from .copysign import TorchCopysignTestCase
from .signbit import TorchSignbitTestCase
from .isneginf import TorchIsneginfTestCase
from .isinf import TorchIsinfTestCase
from .argmin import TorchArgminTestCase
from .quantile import TorchQuantileTestCase
from .logsumexp import TorchLogsumexpTestCase
from ._foreach_reciprocal_ import TorchForeachreciprocalTestCase
from .permute import TorchPermuteTestCase
from .is_tensor import TorchIstensorTestCase
from .fmod import TorchFmodTestCase
from .column_stack import TorchColumnstackTestCase
from .no_grad import TorchNogradTestCase
from .trace import TorchTraceTestCase
from .abs import TorchAbsTestCase
from .logit import TorchLogitTestCase
from .asinh import TorchAsinhTestCase
from .quantize_per_tensor import TorchQuantizepertensorTestCase
from .cdist import TorchCdistTestCase
from .cholesky_inverse import TorchCholeskyinverseTestCase
from .true_divide import TorchTruedivideTestCase
from .subtract import TorchSubtractTestCase
from .std import TorchStdTestCase
from ._foreach_zero_ import TorchForeachzeroTestCase
from .atleast_2d import TorchAtleast2dTestCase
from .arctanh import TorchArctanhTestCase
from .scatter_reduce import TorchScatterreduceTestCase
from .argsort import TorchArgsortTestCase
from .is_complex import TorchIscomplexTestCase
from ._foreach_round import TorchForeachroundTestCase
from .positive import TorchPositiveTestCase
from .erf import TorchErfTestCase
from .atleast_3d import TorchAtleast3dTestCase
from .igammac import TorchIgammacTestCase
from .sym_int import TorchSymintTestCase
from .set_flush_denormal import TorchSetflushdenormalTestCase
from .tanh import TorchTanhTestCase
from .acosh import TorchAcoshTestCase
from ._foreach_round_ import TorchForeachroundTestCase
from .addmv import TorchAddmvTestCase
from .trunc import TorchTruncTestCase
from .cross import TorchCrossTestCase
from .heaviside import TorchHeavisideTestCase
from .lerp import TorchLerpTestCase
from .polar import TorchPolarTestCase
from .cov import TorchCovTestCase
from ._foreach_acos import TorchForeachacosTestCase
from .gt import TorchGtTestCase
from .all import TorchAllTestCase
from .mv import TorchMvTestCase
from ._foreach_atan import TorchForeachatanTestCase
from .amin import TorchAminTestCase
from .logical_or import TorchLogicalorTestCase
from .argwhere import TorchArgwhereTestCase
from ._foreach_log10 import TorchForeachlog10TestCase
from .atleast_1d import TorchAtleast1dTestCase
from .logspace import TorchLogspaceTestCase
from .sqrt import TorchSqrtTestCase
from .t import TorchTTestCase
from .diagflat import TorchDiagflatTestCase
from .take_along_dim import TorchTakealongdimTestCase
from .logical_and import TorchLogicalandTestCase
from .svd import TorchSvdTestCase
from .nanquantile import TorchNanquantileTestCase
from .logcumsumexp import TorchLogcumsumexpTestCase
from .pca_lowrank import TorchPcalowrankTestCase
from .unsqueeze import TorchUnsqueezeTestCase
from .randint import TorchRandintTestCase
from .linspace import TorchLinspaceTestCase
from .isclose import TorchIscloseTestCase
from .repeat_interleave import TorchRepeatinterleaveTestCase
from .logaddexp2 import TorchLogaddexp2TestCase
from .sort import TorchSortTestCase
from .fmin import TorchFminTestCase
from .absolute import TorchAbsoluteTestCase
from .vander import TorchVanderTestCase
from ._foreach_log1p_ import TorchForeachlog1pTestCase
from .le import TorchLeTestCase
from .sym_min import TorchSymminTestCase
from .can_cast import TorchCancastTestCase
from .bernoulli import TorchBernoulliTestCase
from .asin import TorchAsinTestCase
from ._foreach_sin import TorchForeachsinTestCase
from ._foreach_lgamma import TorchForeachlgammaTestCase
from .unique_consecutive import TorchUniqueconsecutiveTestCase
from ._foreach_log10_ import TorchForeachlog10TestCase
from .chunk import TorchChunkTestCase
from .tril import TorchTrilTestCase
from .cartesian_prod import TorchCartesianprodTestCase
from .sym_not import TorchSymnotTestCase
from .set_float32_matmul_precision import TorchSetfloat32matmulprecisionTestCase
from .quantized_max_pool1d import TorchQuantizedmaxpool1dTestCase
from .set_rng_state import TorchSetrngstateTestCase
from .sparse_bsc_tensor import TorchSparsebsctensorTestCase
from .trapezoid import TorchTrapezoidTestCase
from .logical_not import TorchLogicalnotTestCase
from .digamma import TorchDigammaTestCase
from .is_grad_enabled import TorchIsgradenabledTestCase
from .block_diag import TorchBlockdiagTestCase
from .negative import TorchNegativeTestCase
from .ldexp import TorchLdexpTestCase
from ._foreach_exp import TorchForeachexpTestCase
from .use_deterministic_algorithms import TorchUsedeterministicalgorithmsTestCase
from .std_mean import TorchStdmeanTestCase
from ._foreach_cos_ import TorchForeachcosTestCase
from .max import TorchMaxTestCase
from ._foreach_trunc_ import TorchForeachtruncTestCase
from ._foreach_log1p import TorchForeachlog1pTestCase
from .frombuffer import TorchFrombufferTestCase
from .floor import TorchFloorTestCase
from ._foreach_sin_ import TorchForeachsinTestCase
from .multiply import TorchMultiplyTestCase
from .randperm import TorchRandpermTestCase
from .ne import TorchNeTestCase
from .gradient import TorchGradientTestCase
from .get_float32_matmul_precision import TorchGetfloat32matmulprecisionTestCase
from .quantized_max_pool2d import TorchQuantizedmaxpool2dTestCase
from .diagonal_scatter import TorchDiagonalscatterTestCase
from .is_conj import TorchIsconjTestCase
from .pow import TorchPowTestCase
from .norm import TorchNormTestCase
from .det import TorchDetTestCase
from .sparse_csr_tensor import TorchSparsecsrtensorTestCase
from .tensor import TorchTensorTestCase
from .chain_matmul import TorchChainmatmulTestCase
from .cummin import TorchCumminTestCase
from .sgn import TorchSgnTestCase
from .quantized_batch_norm import TorchQuantizedbatchnormTestCase
from .dequantize import TorchDequantizeTestCase
from .dsplit import TorchDsplitTestCase
from .real import TorchRealTestCase
from ._foreach_reciprocal import TorchForeachreciprocalTestCase
from .atan2 import TorchAtan2TestCase
from .renorm import TorchRenormTestCase
from .range import TorchRangeTestCase
from .index_reduce import TorchIndexreduceTestCase
from .matrix_exp import TorchMatrixexpTestCase
from .addr import TorchAddrTestCase
from .broadcast_tensors import TorchBroadcasttensorsTestCase
from .dstack import TorchDstackTestCase
from .where import TorchWhereTestCase
from .diagonal import TorchDiagonalTestCase
from ._foreach_abs_ import TorchForeachabsTestCase
from .bitwise_right_shift import TorchBitwiserightshiftTestCase
from .neg import TorchNegTestCase
from ._foreach_expm1_ import TorchForeachexpm1TestCase
from .mvlgamma import TorchMvlgammaTestCase
from .get_deterministic_debug_mode import TorchGetdeterministicdebugmodeTestCase
from .multinomial import TorchMultinomialTestCase
from .index_add import TorchIndexaddTestCase
from .addbmm import TorchAddbmmTestCase
from .arcsin import TorchArcsinTestCase
from .add import TorchAddTestCase
from .reshape import TorchReshapeTestCase
from .full_like import TorchFulllikeTestCase
from .empty import TorchEmptyTestCase
from .promote_types import TorchPromotetypesTestCase
from .set_warn_always import TorchSetwarnalwaysTestCase
from .is_storage import TorchIsstorageTestCase
from .arange import TorchArangeTestCase
from .is_floating_point import TorchIsfloatingpointTestCase
from .ger import TorchGerTestCase
from .sym_float import TorchSymfloatTestCase
from .frac import TorchFracTestCase
from .float_power import TorchFloatpowerTestCase
from .logical_xor import TorchLogicalxorTestCase
from .median import TorchMedianTestCase
from ._foreach_ceil_ import TorchForeachceilTestCase
from .angle import TorchAngleTestCase
from .from_file import TorchFromfileTestCase
from .triangular_solve import TorchTriangularsolveTestCase
from .nanmean import TorchNanmeanTestCase
from .set_deterministic_debug_mode import TorchSetdeterministicdebugmodeTestCase
from .triu import TorchTriuTestCase
from .ceil import TorchCeilTestCase
from .cholesky import TorchCholeskyTestCase
from .rot90 import TorchRot90TestCase
from .not_equal import TorchNotequalTestCase
from ._foreach_cosh_ import TorchForeachcoshTestCase
from .poisson import TorchPoissonTestCase
from .log import TorchLogTestCase
from .geqrf import TorchGeqrfTestCase
from .sym_ite import TorchSymiteTestCase
from .div import TorchDivTestCase
