from .isin import TorchIsinTestCase
from .unique import TorchUniqueTestCase
from .isposinf import TorchIsposinfTestCase
from .kron import TorchKronTestCase
from .resulttype import TorchResulttypeTestCase
from .enablegrad import TorchEnablegradTestCase
from .stft import TorchStftTestCase
from .full import TorchFullTestCase
from .vdot import TorchVdotTestCase
from .hstack import TorchHstackTestCase
from .broadcastshapes import TorchBroadcastshapesTestCase
from .mean import TorchMeanTestCase
from .orgqr import TorchOrgqrTestCase
from .hannwindow import TorchHannwindowTestCase
from .rand import TorchRandTestCase
from .getnuminteropthreads import TorchGetnuminteropthreadsTestCase
from .cond import TorchCondTestCase
from .nansum import TorchNansumTestCase
from .mode import TorchModeTestCase
from .bucketize import TorchBucketizeTestCase
from .dot import TorchDotTestCase
from .sum import TorchSumTestCase
from .foreachlog import TorchForeachlogTestCase
from .floordivide import TorchFloordivideTestCase
from .exp2 import TorchExp2TestCase
from .foreachsqrt import TorchForeachsqrtTestCase
from .expm1 import TorchExpm1TestCase
from .foreachneg import TorchForeachnegTestCase
from .indexselect import TorchIndexselectTestCase
from .stack import TorchStackTestCase
from .bitwiseand import TorchBitwiseandTestCase
from .foreachasin import TorchForeachasinTestCase
from .bitwiseor import TorchBitwiseorTestCase
from .aredeterministicalgorithmsenabled import TorchAredeterministicalgorithmsenabledTestCase
from .swapdims import TorchSwapdimsTestCase
from .isdeterministicalgorithmswarnonlyenabled import TorchIsdeterministicalgorithmswarnonlyenabledTestCase
from .einsum import TorchEinsumTestCase
from .movedim import TorchMovedimTestCase
from .any import TorchAnyTestCase
from .logdet import TorchLogdetTestCase
from .imag import TorchImagTestCase
from .getdefaultdevice import TorchGetdefaultdeviceTestCase
from .diagembed import TorchDiagembedTestCase
from .isinferencemodeenabled import TorchIsinferencemodeenabledTestCase
from .ge import TorchGeTestCase
from .arctan2 import TorchArctan2TestCase
from .compiledwithcxx11abi import TorchCompiledwithcxx11abiTestCase
from .compile import TorchCompileTestCase
from .setdefaulttensortype import TorchSetdefaulttensortypeTestCase
from .seed import TorchSeedTestCase
from .normal import TorchNormalTestCase
from .pinverse import TorchPinverseTestCase
from .scatter import TorchScatterTestCase
from .lobpcg import TorchLobpcgTestCase
from .nantonum import TorchNantonumTestCase
from .foreachexp import TorchForeachexpTestCase
from .sinc import TorchSincTestCase
from .amax import TorchAmaxTestCase
from .round import TorchRoundTestCase
from .nanmedian import TorchNanmedianTestCase
from .svdlowrank import TorchSvdlowrankTestCase
from .exp import TorchExpTestCase
from .foreachceil import TorchForeachceilTestCase
from .foreachtan import TorchForeachtanTestCase
from .swapaxes import TorchSwapaxesTestCase
from .polygamma import TorchPolygammaTestCase
from .foreachfrac import TorchForeachfracTestCase
from .foreachtrunc import TorchForeachtruncTestCase
from .setnuminteropthreads import TorchSetnuminteropthreadsTestCase
from .minimum import TorchMinimumTestCase
from .bincount import TorchBincountTestCase
from .fliplr import TorchFliplrTestCase
from .nextafter import TorchNextafterTestCase
from .frexp import TorchFrexpTestCase
from .split import TorchSplitTestCase
from .triuindices import TorchTriuindicesTestCase
from .export import TorchExportTestCase
from .viewascomplex import TorchViewascomplexTestCase
from .resolveneg import TorchResolvenegTestCase
from .diag import TorchDiagTestCase
from .take import TorchTakeTestCase
from .i0 import TorchI0TestCase
from .foreachneg import TorchForeachnegTestCase
from .isfinite import TorchIsfiniteTestCase
from .selectscatter import TorchSelectscatterTestCase
from .sin import TorchSinTestCase
from .emptylike import TorchEmptylikeTestCase
from .meshgrid import TorchMeshgridTestCase
from .baddbmm import TorchBaddbmmTestCase
from .diff import TorchDiffTestCase
from .setdefaultdevice import TorchSetdefaultdeviceTestCase
from .hsplit import TorchHsplitTestCase
from .asstrided import TorchAsstridedTestCase
from .manualseed import TorchManualseedTestCase
from .argmax import TorchArgmaxTestCase
from .flip import TorchFlipTestCase
from .msort import TorchMsortTestCase
from .assert import TorchAssertTestCase
from .xlogy import TorchXlogyTestCase
from .outer import TorchOuterTestCase
from .divide import TorchDivideTestCase
from .hammingwindow import TorchHammingwindowTestCase
from .unravelindex import TorchUnravelindexTestCase
from .setprintoptions import TorchSetprintoptionsTestCase
from .tensorsplit import TorchTensorsplitTestCase
from .foreachsinh import TorchForeachsinhTestCase
from .zeroslike import TorchZeroslikeTestCase
from .addcmul import TorchAddcmulTestCase
from .getrngstate import TorchGetrngstateTestCase
from .maximum import TorchMaximumTestCase
from .log10 import TorchLog10TestCase
from .slogdet import TorchSlogdetTestCase
from .clamp import TorchClampTestCase
from .addmm import TorchAddmmTestCase
from .less import TorchLessTestCase
from .var import TorchVarTestCase
from .foreacherfc import TorchForeacherfcTestCase
from .min import TorchMinTestCase
from .emptystrided import TorchEmptystridedTestCase
from .log2 import TorchLog2TestCase
from .foreachlgamma import TorchForeachlgammaTestCase
from .prod import TorchProdTestCase
from .vsplit import TorchVsplitTestCase
from .remainder import TorchRemainderTestCase
from .ormqr import TorchOrmqrTestCase
from .arctan import TorchArctanTestCase
from .unflatten import TorchUnflattenTestCase
from .histogram import TorchHistogramTestCase
from .clone import TorchCloneTestCase
from .vmap import TorchVmapTestCase
from .cummax import TorchCummaxTestCase
from .arccos import TorchArccosTestCase
from .lcm import TorchLcmTestCase
from .setdefaultdtype import TorchSetdefaultdtypeTestCase
from .mul import TorchMulTestCase
from .matmul import TorchMatmulTestCase
from .varmean import TorchVarmeanTestCase
from .moveaxis import TorchMoveaxisTestCase
from .gather import TorchGatherTestCase
from .fmax import TorchFmaxTestCase
from .foreachfloor import TorchForeachfloorTestCase
from .foreachfloor import TorchForeachfloorTestCase
from .symmax import TorchSymmaxTestCase
from .lessequal import TorchLessequalTestCase
from .bartlettwindow import TorchBartlettwindowTestCase
from .foreacherfc import TorchForeacherfcTestCase
from .arccosh import TorchArccoshTestCase
from .randlike import TorchRandlikeTestCase
from .topk import TorchTopkTestCase
from .logaddexp import TorchLogaddexpTestCase
from .foreachabs import TorchForeachabsTestCase
from .complex import TorchComplexTestCase
from .softmax import TorchSoftmaxTestCase
from .sinh import TorchSinhTestCase
from .cumprod import TorchCumprodTestCase
from .sign import TorchSignTestCase
from .fakequantizeperchannelaffine import TorchFakequantizeperchannelaffineTestCase
from .trilindices import TorchTrilindicesTestCase
from .deg2rad import TorchDeg2radTestCase
from .clip import TorchClipTestCase
from .bitwisexor import TorchBitwisexorTestCase
from .cosh import TorchCoshTestCase
from .load import TorchLoadTestCase
from .oneslike import TorchOneslikeTestCase
from .arcsinh import TorchArcsinhTestCase
from .conj import TorchConjTestCase
from .greaterequal import TorchGreaterequalTestCase
from .blackmanwindow import TorchBlackmanwindowTestCase
from .fakequantizepertensoraffine import TorchFakequantizepertensoraffineTestCase
from .lu import TorchLuTestCase
from .atanh import TorchAtanhTestCase
from .cumulativetrapezoid import TorchCumulativetrapezoidTestCase
from .mm import TorchMmTestCase
from .quantizeperchannel import TorchQuantizeperchannelTestCase
from .roll import TorchRollTestCase
from .log1p import TorchLog1pTestCase
from .foreacherf import TorchForeacherfTestCase
from .choleskysolve import TorchCholeskysolveTestCase
from .iswarnalwaysenabled import TorchIswarnalwaysenabledTestCase
from .sigmoid import TorchSigmoidTestCase
from .histc import TorchHistcTestCase
from .inverse import TorchInverseTestCase
from .narrow import TorchNarrowTestCase
from .trapz import TorchTrapzTestCase
from .foreachsqrt import TorchForeachsqrtTestCase
from .squeeze import TorchSqueezeTestCase
from .concat import TorchConcatTestCase
from .searchsorted import TorchSearchsortedTestCase
from .dist import TorchDistTestCase
from .narrowcopy import TorchNarrowcopyTestCase
from .acos import TorchAcosTestCase
from .foreachcos import TorchForeachcosTestCase
from .bitwisenot import TorchBitwisenotTestCase
from .sparsebsrtensor import TorchSparsebsrtensorTestCase
from .bitwiseleftshift import TorchBitwiseleftshiftTestCase
from .sparsecootensor import TorchSparsecootensorTestCase
from .atan import TorchAtanTestCase
from .broadcastto import TorchBroadcasttoTestCase
from .foreachtan import TorchForeachtanTestCase
from .fix import TorchFixTestCase
from .igamma import TorchIgammaTestCase
from .sub import TorchSubTestCase
from .corrcoef import TorchCorrcoefTestCase
from .lt import TorchLtTestCase
from .foreacherf import TorchForeacherfTestCase
from .unbind import TorchUnbindTestCase
from .isreal import TorchIsrealTestCase
from .isnonzero import TorchIsnonzeroTestCase
from .greater import TorchGreaterTestCase
from .foreachasin import TorchForeachasinTestCase
from .getdefaultdtype import TorchGetdefaultdtypeTestCase
from .indexcopy import TorchIndexcopyTestCase
from .fromnumpy import TorchFromnumpyTestCase
from .foreachlog import TorchForeachlogTestCase
from .foreachsigmoid import TorchForeachsigmoidTestCase
from .foreachsigmoid import TorchForeachsigmoidTestCase
from .lusolve import TorchLusolveTestCase
from .sparsecsctensor import TorchSparsecsctensorTestCase
from .combinations import TorchCombinationsTestCase
from .ravel import TorchRavelTestCase
from .ones import TorchOnesTestCase
from .vstack import TorchVstackTestCase
from .scatteradd import TorchScatteraddTestCase
from .numel import TorchNumelTestCase
from .bmm import TorchBmmTestCase
from .qr import TorchQrTestCase
from .foreachacos import TorchForeachacosTestCase
from .inner import TorchInnerTestCase
from .foreachsinh import TorchForeachsinhTestCase
from .erfinv import TorchErfinvTestCase
from .aminmax import TorchAminmaxTestCase
from .tensordot import TorchTensordotTestCase
from .rowstack import TorchRowstackTestCase
from .maskedselect import TorchMaskedselectTestCase
from .rad2deg import TorchRad2degTestCase
from .astensor import TorchAstensorTestCase
from .allclose import TorchAllcloseTestCase
from .isnan import TorchIsnanTestCase
from .initialseed import TorchInitialseedTestCase
from .hypot import TorchHypotTestCase
from .randn import TorchRandnTestCase
from .kthvalue import TorchKthvalueTestCase
from .fromdlpack import TorchFromdlpackTestCase
from .addcdiv import TorchAddcdivTestCase
from .select import TorchSelectTestCase
from .slicescatter import TorchSlicescatterTestCase
from .setnumthreads import TorchSetnumthreadsTestCase
from .rsqrt import TorchRsqrtTestCase
from .luunpack import TorchLuunpackTestCase
from .viewasreal import TorchViewasrealTestCase
from .tile import TorchTileTestCase
from .getnumthreads import TorchGetnumthreadsTestCase
from .nonzero import TorchNonzeroTestCase
from .save import TorchSaveTestCase
from .cat import TorchCatTestCase
from .randnlike import TorchRandnlikeTestCase
from .eq import TorchEqTestCase
from .foreachcosh import TorchForeachcoshTestCase
from .foreachatan import TorchForeachatanTestCase
from .select import TorchSelectTestCase
from .resolveconj import TorchResolveconjTestCase
from .tan import TorchTanTestCase
from .countnonzero import TorchCountnonzeroTestCase
from .foreachlog2 import TorchForeachlog2TestCase
from .lgamma import TorchLgammaTestCase
from .reciprocal import TorchReciprocalTestCase
from .transpose import TorchTransposeTestCase
from .square import TorchSquareTestCase
from .concatenate import TorchConcatenateTestCase
from .cos import TorchCosTestCase
from .matrixpower import TorchMatrixpowerTestCase
from .asarray import TorchAsarrayTestCase
from .flipud import TorchFlipudTestCase
from .cumsum import TorchCumsumTestCase
from .adjoint import TorchAdjointTestCase
from .erfc import TorchErfcTestCase
from .conjphysical import TorchConjphysicalTestCase
from .flatten import TorchFlattenTestCase
from .eye import TorchEyeTestCase
from .gcd import TorchGcdTestCase
from .foreachfrac import TorchForeachfracTestCase
from .foreachlog2 import TorchForeachlog2TestCase
from .kaiserwindow import TorchKaiserwindowTestCase
from .foreachexpm1 import TorchForeachexpm1TestCase
from .zeros import TorchZerosTestCase
from .Generator import TorchGeneratorTestCase
from .istft import TorchIstftTestCase
from .histogramdd import TorchHistogramddTestCase
from .equal import TorchEqualTestCase
from .randintlike import TorchRandintlikeTestCase
from .copysign import TorchCopysignTestCase
from .signbit import TorchSignbitTestCase
from .isneginf import TorchIsneginfTestCase
from .isinf import TorchIsinfTestCase
from .argmin import TorchArgminTestCase
from .quantile import TorchQuantileTestCase
from .logsumexp import TorchLogsumexpTestCase
from .foreachreciprocal import TorchForeachreciprocalTestCase
from .permute import TorchPermuteTestCase
from .istensor import TorchIstensorTestCase
from .fmod import TorchFmodTestCase
from .columnstack import TorchColumnstackTestCase
from .nograd import TorchNogradTestCase
from .trace import TorchTraceTestCase
from .abs import TorchAbsTestCase
from .logit import TorchLogitTestCase
from .asinh import TorchAsinhTestCase
from .quantizepertensor import TorchQuantizepertensorTestCase
from .cdist import TorchCdistTestCase
from .choleskyinverse import TorchCholeskyinverseTestCase
from .truedivide import TorchTruedivideTestCase
from .subtract import TorchSubtractTestCase
from .std import TorchStdTestCase
from .foreachzero import TorchForeachzeroTestCase
from .atleast2d import TorchAtleast2dTestCase
from .arctanh import TorchArctanhTestCase
from .scatterreduce import TorchScatterreduceTestCase
from .argsort import TorchArgsortTestCase
from .iscomplex import TorchIscomplexTestCase
from .foreachround import TorchForeachroundTestCase
from .positive import TorchPositiveTestCase
from .erf import TorchErfTestCase
from .atleast3d import TorchAtleast3dTestCase
from .igammac import TorchIgammacTestCase
from .symint import TorchSymintTestCase
from .setflushdenormal import TorchSetflushdenormalTestCase
from .tanh import TorchTanhTestCase
from .acosh import TorchAcoshTestCase
from .foreachround import TorchForeachroundTestCase
from .addmv import TorchAddmvTestCase
from .trunc import TorchTruncTestCase
from .cross import TorchCrossTestCase
from .heaviside import TorchHeavisideTestCase
from .lerp import TorchLerpTestCase
from .polar import TorchPolarTestCase
from .cov import TorchCovTestCase
from .foreachacos import TorchForeachacosTestCase
from .gt import TorchGtTestCase
from .all import TorchAllTestCase
from .mv import TorchMvTestCase
from .foreachatan import TorchForeachatanTestCase
from .amin import TorchAminTestCase
from .logicalor import TorchLogicalorTestCase
from .argwhere import TorchArgwhereTestCase
from .foreachlog10 import TorchForeachlog10TestCase
from .atleast1d import TorchAtleast1dTestCase
from .logspace import TorchLogspaceTestCase
from .sqrt import TorchSqrtTestCase
from .t import TorchTTestCase
from .diagflat import TorchDiagflatTestCase
from .takealongdim import TorchTakealongdimTestCase
from .logicaland import TorchLogicalandTestCase
from .svd import TorchSvdTestCase
from .nanquantile import TorchNanquantileTestCase
from .logcumsumexp import TorchLogcumsumexpTestCase
from .pcalowrank import TorchPcalowrankTestCase
from .unsqueeze import TorchUnsqueezeTestCase
from .randint import TorchRandintTestCase
from .linspace import TorchLinspaceTestCase
from .isclose import TorchIscloseTestCase
from .repeatinterleave import TorchRepeatinterleaveTestCase
from .logaddexp2 import TorchLogaddexp2TestCase
from .sort import TorchSortTestCase
from .fmin import TorchFminTestCase
from .absolute import TorchAbsoluteTestCase
from .vander import TorchVanderTestCase
from .foreachlog1p import TorchForeachlog1pTestCase
from .le import TorchLeTestCase
from .symmin import TorchSymminTestCase
from .cancast import TorchCancastTestCase
from .bernoulli import TorchBernoulliTestCase
from .asin import TorchAsinTestCase
from .foreachsin import TorchForeachsinTestCase
from .foreachlgamma import TorchForeachlgammaTestCase
from .uniqueconsecutive import TorchUniqueconsecutiveTestCase
from .foreachlog10 import TorchForeachlog10TestCase
from .chunk import TorchChunkTestCase
from .tril import TorchTrilTestCase
from .cartesianprod import TorchCartesianprodTestCase
from .symnot import TorchSymnotTestCase
from .setfloat32matmulprecision import TorchSetfloat32matmulprecisionTestCase
from .quantizedmaxpool1d import TorchQuantizedmaxpool1dTestCase
from .setrngstate import TorchSetrngstateTestCase
from .sparsebsctensor import TorchSparsebsctensorTestCase
from .trapezoid import TorchTrapezoidTestCase
from .logicalnot import TorchLogicalnotTestCase
from .digamma import TorchDigammaTestCase
from .isgradenabled import TorchIsgradenabledTestCase
from .blockdiag import TorchBlockdiagTestCase
from .negative import TorchNegativeTestCase
from .ldexp import TorchLdexpTestCase
from .foreachexp import TorchForeachexpTestCase
from .usedeterministicalgorithms import TorchUsedeterministicalgorithmsTestCase
from .stdmean import TorchStdmeanTestCase
from .foreachcos import TorchForeachcosTestCase
from .max import TorchMaxTestCase
from .foreachtrunc import TorchForeachtruncTestCase
from .foreachlog1p import TorchForeachlog1pTestCase
from .frombuffer import TorchFrombufferTestCase
from .floor import TorchFloorTestCase
from .foreachsin import TorchForeachsinTestCase
from .multiply import TorchMultiplyTestCase
from .randperm import TorchRandpermTestCase
from .ne import TorchNeTestCase
from .gradient import TorchGradientTestCase
from .getfloat32matmulprecision import TorchGetfloat32matmulprecisionTestCase
from .quantizedmaxpool2d import TorchQuantizedmaxpool2dTestCase
from .diagonalscatter import TorchDiagonalscatterTestCase
from .isconj import TorchIsconjTestCase
from .pow import TorchPowTestCase
from .norm import TorchNormTestCase
from .det import TorchDetTestCase
from .sparsecsrtensor import TorchSparsecsrtensorTestCase
from .tensor import TorchTensorTestCase
from .chainmatmul import TorchChainmatmulTestCase
from .cummin import TorchCumminTestCase
from .sgn import TorchSgnTestCase
from .quantizedbatchnorm import TorchQuantizedbatchnormTestCase
from .dequantize import TorchDequantizeTestCase
from .dsplit import TorchDsplitTestCase
from .real import TorchRealTestCase
from .foreachreciprocal import TorchForeachreciprocalTestCase
from .atan2 import TorchAtan2TestCase
from .renorm import TorchRenormTestCase
from .range import TorchRangeTestCase
from .indexreduce import TorchIndexreduceTestCase
from .matrixexp import TorchMatrixexpTestCase
from .addr import TorchAddrTestCase
from .broadcasttensors import TorchBroadcasttensorsTestCase
from .dstack import TorchDstackTestCase
from .where import TorchWhereTestCase
from .diagonal import TorchDiagonalTestCase
from .foreachabs import TorchForeachabsTestCase
from .bitwiserightshift import TorchBitwiserightshiftTestCase
from .neg import TorchNegTestCase
from .foreachexpm1 import TorchForeachexpm1TestCase
from .mvlgamma import TorchMvlgammaTestCase
from .getdeterministicdebugmode import TorchGetdeterministicdebugmodeTestCase
from .multinomial import TorchMultinomialTestCase
from .indexadd import TorchIndexaddTestCase
from .addbmm import TorchAddbmmTestCase
from .arcsin import TorchArcsinTestCase
from .add import TorchAddTestCase
from .reshape import TorchReshapeTestCase
from .fulllike import TorchFulllikeTestCase
from .empty import TorchEmptyTestCase
from .promotetypes import TorchPromotetypesTestCase
from .setwarnalways import TorchSetwarnalwaysTestCase
from .isstorage import TorchIsstorageTestCase
from .arange import TorchArangeTestCase
from .isfloatingpoint import TorchIsfloatingpointTestCase
from .ger import TorchGerTestCase
from .symfloat import TorchSymfloatTestCase
from .frac import TorchFracTestCase
from .floatpower import TorchFloatpowerTestCase
from .logicalxor import TorchLogicalxorTestCase
from .median import TorchMedianTestCase
from .foreachceil import TorchForeachceilTestCase
from .angle import TorchAngleTestCase
from .fromfile import TorchFromfileTestCase
from .triangularsolve import TorchTriangularsolveTestCase
from .nanmean import TorchNanmeanTestCase
from .setdeterministicdebugmode import TorchSetdeterministicdebugmodeTestCase
from .triu import TorchTriuTestCase
from .ceil import TorchCeilTestCase
from .cholesky import TorchCholeskyTestCase
from .rot90 import TorchRot90TestCase
from .notequal import TorchNotequalTestCase
from .foreachcosh import TorchForeachcoshTestCase
from .poisson import TorchPoissonTestCase
from .log import TorchLogTestCase
from .geqrf import TorchGeqrfTestCase
from .symite import TorchSymiteTestCase
from .div import TorchDivTestCase
