from .register_module_forward_pre_hook import TorchNnModulesModuleRegistermoduleforwardprehookTestCase
from .register_module_forward_hook import TorchNnModulesModuleRegistermoduleforwardhookTestCase
from .register_module_buffer_registration_hook import TorchNnModulesModuleRegistermodulebufferregistrationhookTestCase
from .register_module_full_backward_hook import TorchNnModulesModuleRegistermodulefullbackwardhookTestCase
from .register_module_module_registration_hook import TorchNnModulesModuleRegistermodulemoduleregistrationhookTestCase
from .register_module_full_backward_pre_hook import TorchNnModulesModuleRegistermodulefullbackwardprehookTestCase
from .register_module_parameter_registration_hook import TorchNnModulesModuleRegistermoduleparameterregistrationhookTestCase
from .register_module_backward_hook import TorchNnModulesModuleRegistermodulebackwardhookTestCase
