from .registermoduleforwardprehook import TorchNnModulesModuleRegistermoduleforwardprehookTestCase
from .registermoduleforwardhook import TorchNnModulesModuleRegistermoduleforwardhookTestCase
from .registermodulebufferregistrationhook import TorchNnModulesModuleRegistermodulebufferregistrationhookTestCase
from .registermodulefullbackwardhook import TorchNnModulesModuleRegistermodulefullbackwardhookTestCase
from .registermodulemoduleregistrationhook import TorchNnModulesModuleRegistermodulemoduleregistrationhookTestCase
from .registermodulefullbackwardprehook import TorchNnModulesModuleRegistermodulefullbackwardprehookTestCase
from .registermoduleparameterregistrationhook import TorchNnModulesModuleRegistermoduleparameterregistrationhookTestCase
from .registermodulebackwardhook import TorchNnModulesModuleRegistermodulebackwardhookTestCase
